import test from 'node:test';import assert from 'node:assert/strict';import {handleAccess,loadApprovedStudents,usesPortalRegistry} from './access-handler.mjs';
const request=(studentId,origin='http://localhost')=>new Request('http://localhost/api/student-access',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({studentId})});
test('only unique approved ID verifies without exposing profile',async()=>{const r=await handleAccess(request(' und1_000001 '),async()=>[{id:'UND1_000001',status:'approved',name:'PRIVATE'}]);assert.deepEqual(await r.json(),{verified:true,message:'Cadastro aprovado localizado. A secretaria deverá conferir a identidade do responsável para prosseguir. O atendimento só será confirmado por WhatsApp ao aluno ou responsável.'})});
test('unknown pending inactive and duplicate IDs never verify',async()=>{for(const entries of [[],[{id:'UND1_000001',status:'pending'}],[{id:'UND1_000001',status:'inactive'}],[{id:'UND1_000001',status:'approved'},{id:'UND1_000001',status:'approved'}]])assert.equal((await (await handleAccess(request('UND1_000001'),async()=>entries)).json()).verified,false)});
test('demo is separate and cannot verify as real student',async()=>{const d=await (await handleAccess(request('TREINO_UND1_000001'),()=>assert.fail())).json();assert.equal(d.verified,false);assert.equal(d.training,true)});
test('registry failure and bad origin fail closed',async()=>{assert.equal((await handleAccess(request('UND1_000001'),async()=>{throw Error()})).status,503);assert.equal((await handleAccess(request('UND1_000001','https://foreign.invalid'))).status,403)});
test('Aprovação: portal configurado usa cadastro atual, mesmo sem a chave antiga ou com ela desativada',async()=>{
 for(const flag of [undefined,'false','true']){const env={PORTAL_DATA_DIR:'isolated-test',PORTAL_SECRET:'test-only-'.repeat(4),PORTAL_REGISTRY_ACTIVE:flag,APPROVED_STUDENTS_JSON:JSON.stringify({version:1,students:[]})};let status='approved';const source=()=>({students:async()=>[{id:'UND2_000001',status,name:'PRIVATE',birth_date:'PRIVATE'}]});assert.equal(usesPortalRegistry(env),true);assert.deepEqual(await loadApprovedStudents(env,source),[{id:'UND2_000001',status:'approved'}]);assert.equal((await (await handleAccess(request('UND2_000001'),()=>loadApprovedStudents(env,source))).json()).verified,true);status='inactive';assert.equal((await (await handleAccess(request('UND2_000001'),()=>loadApprovedStudents(env,source))).json()).verified,false)}
});
test('Aprovação: falha no banco não recorre a uma lista antiga; legado somente sem portal configurado',async()=>{
 const legacy=JSON.stringify({version:1,students:[{id:'UND2_000001',status:'approved'}]}),env={PORTAL_DATA_DIR:'isolated-test',PORTAL_SECRET:'test-only-'.repeat(4),APPROVED_STUDENTS_JSON:legacy};await assert.rejects(loadApprovedStudents(env,()=>{throw Error('Database unavailable')}));assert.deepEqual(await loadApprovedStudents({APPROVED_STUDENTS_JSON:legacy},()=>assert.fail()),[{id:'UND2_000001',status:'approved'}]);assert.equal(usesPortalRegistry({}),false);
});
