import test from 'node:test';import assert from 'node:assert/strict';import {handleAgenda,agendaStatus,DEMO_ID} from './agenda-handler.mjs';
const env={RESEND_API_KEY:'mock',MAIL_FROM:'Projeto <teste@example.invalid>'};
const sample={studentId:DEMO_ID,service:'Psicologia',date:'2099-10-13',weekday:new Date('2099-10-13T12:00:00Z').getUTCDay(),time:'23:59',consent:true,requestId:'aabbccdd-0000-4000-8000-001122334455'};
const req=(changes={},origin='http://localhost')=>new Request('http://localhost/api/training-agenda',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({...sample,...changes})});
test('missing transport is unavailable and never sends',async()=>{assert.equal(agendaStatus({}).Psicologia,false);assert.equal((await handleAgenda(req(),{},()=>assert.fail('must not send'))).status,503)});
for(const [service,email]of [['Psicologia','psicologa@projetolutapelacomunidade.com.br'],['Assistência social','assistente.social@projetolutapelacomunidade.com.br']])test('routes only to correct professional: '+service,async()=>{let payload;const r=await handleAgenda(req({service,to:['intruder@example.invalid']}),env,async(u,o)=>{payload=JSON.parse(o.body);return Response.json({id:'mock-send'})});assert.equal(r.status,200);assert.deepEqual(payload.to,['agenda@projetolutapelacomunidade.com.br','tezzei@gmail.com',email]);assert.match(payload.subject,/TREINAMENTO/);assert.ok(!payload.attachments);assert.ok(!payload.text.includes('TEA'))});
test('rejects wrong ID, unknown service, consent and mismatched day',async()=>{for(const changes of [{studentId:'UND1_000001'},{service:'Outro'},{consent:false},{weekday:(sample.weekday+1)%7},{date:'2099-02-30'},{time:'24:00'},{date:'2020-01-01',weekday:3}])assert.equal((await handleAgenda(req(changes),env,()=>assert.fail('must not send'))).status,400)});
test('rejects foreign origin',async()=>assert.equal((await handleAgenda(req({},'https://foreign.invalid'),env)).status,403));
test('provider error cannot become success',async()=>assert.equal((await handleAgenda(req(),env,async()=>Response.json({}, {status:500}))).status,502));
