import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {JSDOM} from 'jsdom';
import {mountAttendanceTools,createAttendanceDraftCache} from './dist/portal/attendance-mobile.js';
import {mountAttendanceHistory} from './dist/portal/attendance-history.js';
const memory=()=>{const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k),data}};
test('Rascunho móvel: recarregar preserva escolhas e versões, expira com sessão e não atravessa contas',()=>{
 const storage=memory(),user={user_id:'teacher-a',session_expires_at:9000},draft=new Map([['class-a',new Map([['UND1_000001',{status:'absent',version:2,dirty:true,name:'Nome privado'}],['UND1_000002',{status:'present',version:5,dirty:false}]])]]),cache=createAttendanceDraftCache(storage,()=>1000);cache.save(user,draft);const restored=cache.read(user);assert.equal(restored.get('class-a').size,1);assert.deepEqual(restored.get('class-a').get('UND1_000001'),{status:'absent',version:2,dirty:true});assert.doesNotMatch([...storage.data.values()].join(''),/Nome privado/);
 assert.equal(cache.read({user_id:'teacher-b'}).size,0);cache.save(user,draft);assert.equal(createAttendanceDraftCache(storage,()=>9000).read(user).size,0);cache.save(user,draft);cache.clear();assert.equal(cache.read(user).size,0);
});
test('Rascunho móvel: armazenamento indisponível não impede a chamada',()=>{
 const storage={getItem(){throw Error()},setItem(){throw Error()},removeItem(){throw Error()}},cache=createAttendanceDraftCache(storage);assert.equal(cache.read({user_id:'x'}).size,0);assert.equal(cache.save({user_id:'x'},new Map([['a',new Map([['s',{status:'present',version:0,dirty:true}]])]])),false);assert.doesNotThrow(()=>cache.clear());
});
function ui(t,{write=true,fail=false}={}){
 const dom=new JSDOM('<main><div id="attendance-area" class="is-current"><div id="class-detail"></div></div><div id="team-area"></div></main>',{url:'https://example.test/professor/',runScripts:'outside-only'}),w=dom.window,context=dom.getInternalVMContext(),errors=[],requests=[];t.after(()=>{w.close();assert.deepEqual(errors,[])});dom.virtualConsole.on('jsdomError',e=>errors.push(e.message));w.HTMLElement.prototype.scrollIntoView=function(){};
 const rows=[{id:'UND1_000001',name:'Álvaro Fictício',status:'unmarked',version:0},{id:'UND1_000002',name:'Beatriz Fictícia',status:'unmarked',version:0}],history=[],model={fail};
 w.modules={mobile:{mountAttendanceTools,createAttendanceDraftCache},history:{mountAttendanceHistory},photo:{mountClassEvidence:async()=>{}},rollcall:{startRollcallPanel:()=>{}}};
 w.api=async(url,opts)=>{requests.push({url,...opts});if(url.endsWith('/attendance')&&!opts)return {lesson:{id:'class-a',label:'Turma fictícia',unit:'amavale',day:'2020-01-01',time:'15:00'},students:structuredClone(rows),can_write:write};if(url.includes('attendance-history'))return {changes:history,next_before:null};if(url.endsWith('/attendance')&&opts){if(model.fail)throw Error('Sem conexão. Tente novamente.');for(const r of opts.data.rows){const old=rows.find(x=>x.id===r.id);history.unshift({id:history.length+1,student_id:r.id,student_name:old.name,previous_status:old.status,status:r.status,version:r.version+1,actor_name:'Professor Fictício',actor_role:'teacher',created_at:new Date().toISOString(),kind:'change'});Object.assign(old,{...r,version:r.version+1,updated_by_name:'Professor Fictício',updated_at:new Date().toISOString()})}return {message:'Chamada salva.'}}throw Error('Unexpected '+url)};
 vm.runInContext(`const $=id=>document.getElementById(id);let me={user_id:'teacher',role:'teacher',session_expires_at:Date.now()+3600000};const notice=message=>document.body.dataset.notice=message;
 function el(tag,text,attrs={}){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);return e}
 function field(host,label,name,value='',opts={}){const e=el('input',undefined,{id:name,name,type:opts.type||'text'});e.value=value;host.append(el('label',label,{for:name}),e);return e}
 `,context);vm.runInContext(fs.readFileSync(new URL('./dist/portal/action.js',import.meta.url),'utf8'),context);vm.runInContext('const action=createPortalAction({notice,el});',context);
 let source=fs.readFileSync(new URL('./dist/portal/attendance.js',import.meta.url),'utf8');for(const [file,key]of [['attendance-mobile.js','mobile'],['attendance-history.js','history'],['class-evidence.js','photo'],['rollcall-panel.js','rollcall']])source=source.replaceAll(`import('./${file}')`,`Promise.resolve(modules.${key})`);
 vm.runInContext(source,context);return {w,rows,requests,model,run:code=>vm.runInContext(code,context)};
}
test('Chamada móvel: um toque marca, busca não perde escolhas e próximo não marcado mantém contexto',async t=>{
 const f=ui(t);await f.run("classDetail('class-a')");const buttons=f.w.document.querySelectorAll('[data-status=present]');buttons[0].click();assert.equal(buttons[0].getAttribute('aria-pressed'),'true');assert.match(f.w.document.querySelector('.save-call').textContent,/1 de 2 marcados.*1 alteração/);
 const search=f.w.document.querySelector('[type=search]');search.value='alvaro';search.dispatchEvent(new f.w.Event('input'));assert.equal(f.w.document.querySelectorAll('fieldset[hidden]').length,1);f.w.document.querySelector('.attendance-toolbar button').click();assert.equal(f.w.document.activeElement.dataset.studentId,'UND1_000002');assert.equal(search.value,'');assert.equal(buttons[0].getAttribute('aria-pressed'),'true');assert.equal(f.requests.filter(r=>r.method==='POST').length,0);
});
test('Chamada móvel: falha preserva rascunho e nova tentativa salva somente mudanças com autoria',async t=>{
 const f=ui(t,{fail:true});await f.run("classDetail('class-a')");f.w.document.querySelector('[data-status=present]').click();let form=f.w.document.querySelector('.attendance-form');form.dispatchEvent(new f.w.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));assert.match(form.textContent,/Sem conexão/);assert.equal(f.rows[0].status,'unmarked');assert.equal(form.querySelector('[data-status=present]').getAttribute('aria-pressed'),'true');assert.equal(form.querySelector('.save-call button').disabled,false);
 f.model.fail=false;form.dispatchEvent(new f.w.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));assert.equal(f.rows[0].status,'present');assert.equal(f.rows[1].status,'unmarked');assert.match(f.w.document.querySelector('.attendance-attribution').textContent,/Professor Fictício/);assert.equal(f.w.document.querySelector('.save-call button').disabled,true);assert.equal(f.requests.find(r=>r.method==='POST').data.rows.length,1);
});
test('Chamada móvel: secretaria de núcleo só consulta e histórico usa texto seguro',async t=>{
 const f=ui(t,{write:false});await f.run("classDetail('class-a')");assert.equal(f.w.document.querySelectorAll('.attendance-choice').length,0);assert.equal(f.w.document.querySelector('.save-call button'),null);assert.match(f.w.document.body.textContent,/Somente consulta/);assert.doesNotMatch(f.w.document.body.textContent,/Confirmar cancelamento/);
});
test('Chamada móvel: fotos indisponíveis não bloqueiam a marcação nem o salvamento',async t=>{
 const f=ui(t);f.w.modules.photo.mountClassEvidence=async()=>{throw Error('Sem fotos')};await f.run("classDetail('class-a')");assert.match(f.w.document.querySelector('.class-evidence').textContent,/continuar lançando/);f.w.document.querySelector('[data-status=present]').click();f.w.document.querySelector('.attendance-form').dispatchEvent(new f.w.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));assert.equal(f.rows[0].status,'present');assert.match(f.w.document.body.dataset.notice,/gravadas/);
});
test('Chamada móvel: confirmação de gravação é preservada quando apenas a recarga falha',async t=>{
 const f=ui(t);await f.run("classDetail('class-a')");const api=f.w.api;let saved=false;f.w.api=async(url,opts)=>{if(saved&&!opts&&url.endsWith('/attendance'))throw Error('Falha na recarga');const result=await api(url,opts);if(opts?.method==='POST')saved=true;return result};f.w.document.querySelector('[data-status=present]').click();f.w.document.querySelector('.attendance-form').dispatchEvent(new f.w.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));assert.equal(f.rows[0].status,'present');assert.match(f.w.document.querySelector('#class-detail').textContent,/Chamada salva.*Não foi possível recarregar/);assert.equal(f.run('attendanceDrafts.size'),0);assert.equal(f.requests.filter(r=>r.method==='POST').length,1);
});
async function syncFixture(t,revoked=false){
 const dom=new JSDOM('<section id="class-detail"><p>Chamada aberta</p></section><section id="staff-detail">Cadastro antigo</section>',{runScripts:'outside-only'});t.after(()=>dom.window.close());const context=dom.getInternalVMContext();vm.runInContext(`const $=id=>document.getElementById(id);let classSelected='call-a',currentPanel='attendance-area',me={role:'teacher'},token='session',chosen='',students=[],attendanceDrafts=new Map();let reloaded=null;const api=async()=>({role:'teacher'}),el=()=>{},load=async()=>{},notice=m=>document.body.dataset.notice=m;const classDetail=async id=>{reloaded=id;${revoked?"throw Error('Acesso à turma revogado')":"$('class-detail').textContent='Chamada atualizada';$('class-detail').hidden=false"}};const capture=options=>window.sync=options;`,context);
 let source=fs.readFileSync(new URL('./dist/portal/portal.js',import.meta.url),'utf8').split("import('/portal/system-sync.js')")[1].split("import('/portal/absence-attention.js')")[0];source="Promise.resolve({startSystemSync:capture})"+source;vm.runInContext(source,context);await new Promise(r=>setImmediate(r));await dom.window.sync.refresh();return {w:dom.window,run:code=>vm.runInContext(code,context)};
}
test('Chamada móvel: sincronização recarrega chamada aberta sem devolver professor à lista',async t=>{
 const f=await syncFixture(t);assert.equal(f.run('reloaded'),'call-a');assert.equal(f.w.document.querySelector('#class-detail').hidden,false);assert.equal(f.w.document.querySelector('#class-detail').textContent,'Chamada atualizada');assert.equal(f.w.document.querySelector('#staff-detail').hidden,true);
});
test('Chamada móvel: sincronização remove dados da chamada quando autorização é revogada',async t=>{
 const f=await syncFixture(t,true);assert.equal(f.w.document.querySelector('#class-detail').hidden,true);assert.equal(f.w.document.querySelector('#class-detail').textContent,'');assert.match(f.w.document.body.dataset.notice,/revogado/);
});
