import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {JSDOM} from 'jsdom';
const settle=()=>new Promise(r=>setTimeout(r,20));
function ui(t,role='admin'){
 const dom=new JSDOM('<div id="workspace"></div>',{url:'https://example.test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,run=s=>vm.runInContext(s,dom.getInternalVMContext());t.after(()=>w.close());w.HTMLElement.prototype.scrollIntoView=()=>{};
 const portal=fs.readFileSync(new URL('./dist/portal/portal.js',import.meta.url),'utf8');run(portal.slice(portal.indexOf('function el('),portal.indexOf('function notice(')));run('let fieldSequence=0;'+portal.slice(portal.indexOf('function field('),portal.indexOf('async function detail(')));run(fs.readFileSync(new URL('./dist/portal/action.js',import.meta.url),'utf8'));
 w.calls=[];w.errors=[];w.data={settings:{configured:true,key_id:'fingerprint',key_saved:true,enabled:true,interval_hours:4,drive_folder:'',drive_connected:false,version:2},packages:[],external_pending:true,restore_pending:true,overdue:false};w.me={role};w.$=id=>w.document.getElementById(id);w.notice=(msg,error)=>{if(error)w.errors.push(msg)};w.api=async(route,opts)=>{w.calls.push({route,opts});if(opts?.method==='PATCH')throw Error('Conflito de versão de teste');return w.data};w.download=()=>{};run('const action=createPortalAction({notice,el});');run(fs.readFileSync(new URL('./dist/portal/backups.js',import.meta.url),'utf8'));return {w,run,async start(){w.document.dispatchEvent(new w.Event('portal:loaded'));await settle()}};
}
test('painel distingue Drive pendente, preserva formulário com erro e exige nova confirmação após trocar chave',async t=>{
 const u=ui(t);await u.start();const d=u.w.document;assert.match(d.getElementById('backup-attention').textContent,/Drive/);assert.match(d.getElementById('backup-content').textContent,/autorização da API/);const key=d.getElementById('backup-public-key'),form=key.form;key.value='PUBLIC KEY fixture';key.dispatchEvent(new u.w.Event('input'));assert.equal(form.elements.key_saved.value,'false');form.elements.key_saved.value='true';form.dispatchEvent(new u.w.Event('submit',{cancelable:true}));await settle();assert.equal(key.value,'PUBLIC KEY fixture');assert.equal(u.w.errors.length,1);assert.equal(u.w.calls.at(-1).opts.data.version,2);
 u.w.me=null;d.dispatchEvent(new u.w.Event('portal:logout'));assert.equal(d.getElementById('backup-area'),null);assert.equal(d.getElementById('backup-attention'),null);
});
test('perfis restritos não carregam nem exibem backups',async t=>{const u=ui(t,'teacher');await u.start();assert.equal(u.w.calls.length,0);assert.equal(u.w.document.getElementById('backup-area'),null)});

test('painel informa destinatários, horário e confirmação real dos avisos por email',async t=>{const u=ui(t);u.w.data.notifications={configured:true,recipients:['admin@example.test'],pending:1,unconfirmed:2,last_accepted:{accepted_at:'2026-10-10T11:00:00Z'}};u.w.data.external_pending=false;u.w.data.restore_pending=false;await u.start();const text=u.w.document.getElementById('backup-content').textContent;assert.match(text,/Resumo diário às 8h/);assert.match(text,/admin@example.test/);assert.match(text,/aceito pelo serviço/);assert.match(text,/não comprova entrega/);assert.match(u.w.document.getElementById('backup-attention').textContent,/email sem confirmação/)});
