import {randomUUID} from 'node:crypto';
import {fail} from './portal-domain.mjs';
const prefix={amavale:'UND1_',valparaiso:'UND2_','vale-do-carangola':'UND3_'};
export function classGroups({db,get,all,run,tx,requireRole,requireUnit,audit}){
 db.exec(`CREATE TABLE IF NOT EXISTS class_groups(id TEXT PRIMARY KEY,unit TEXT NOT NULL,label TEXT NOT NULL,weekdays TEXT NOT NULL,start_time TEXT NOT NULL,end_time TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,version INTEGER NOT NULL DEFAULT 1);
 CREATE TABLE IF NOT EXISTS group_students(group_id TEXT NOT NULL REFERENCES class_groups(id),student_id TEXT NOT NULL REFERENCES students(id),PRIMARY KEY(group_id,student_id));
 CREATE TABLE IF NOT EXISTS class_students(class_id TEXT NOT NULL REFERENCES classes(id),student_id TEXT NOT NULL REFERENCES students(id),PRIMARY KEY(class_id,student_id));`);
 if(!all('PRAGMA table_info(classes)').some(c=>c.name==='group_id'))db.exec('ALTER TABLE classes ADD COLUMN group_id TEXT REFERENCES class_groups(id)');
 const read=(actor,id)=>{const g=get('SELECT * FROM class_groups WHERE id=?',id);if(!g)fail('Turma não localizada.',404);requireUnit(actor,g.unit);return {...g,weekdays:JSON.parse(g.weekdays),active:!!g.active}};
 return {
  groupRead:read,
  async groups(actor,unit){requireUnit(actor,unit);return all('SELECT g.*,COUNT(gs.student_id) AS enrolled FROM class_groups g LEFT JOIN group_students gs ON gs.group_id=g.id WHERE g.unit=? GROUP BY g.id ORDER BY start_time,label',unit).map(g=>({...g,weekdays:JSON.parse(g.weekdays),active:!!g.active}))},
  async group(actor,id){const g=read(actor,id);return {...g,students:all("SELECT s.id,s.name,EXISTS(SELECT 1 FROM group_students gs WHERE gs.group_id=? AND gs.student_id=s.id) AS enrolled FROM students s WHERE substr(s.id,1,5)=? AND s.status='approved' ORDER BY s.name,s.id",id,prefix[g.unit]).map(s=>({...s,enrolled:!!s.enrolled}))}},
  async saveGroup(actor,id,p){return tx(()=>{requireRole(actor,['admin','secretary']);requireUnit(actor,p.unit);if(typeof p.label!=='string'||p.label.trim().length<3||p.label.length>100||/[\x00-\x1f]/.test(p.label)||!Array.isArray(p.weekdays)||!p.weekdays.length||p.weekdays.length>7||new Set(p.weekdays).size!==p.weekdays.length||p.weekdays.some(d=>!Number.isInteger(d)||d<0||d>6)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(p.start_time)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(p.end_time)||p.end_time<=p.start_time||typeof p.active!=='boolean'||!Number.isSafeInteger(p.version))fail('Confira turma, dias e horários.');const old=id?read(actor,id):null;if((old?.version||0)!==p.version)fail('Turma alterada. Reabra antes de salvar.',409);if(old&&old.unit!==p.unit)fail('O núcleo da turma não pode ser alterado.');if(!Array.isArray(p.students)||p.students.length>500||new Set(p.students).size!==p.students.length)fail('Lista de matrícula inválida.');for(const sid of p.students){const s=get('SELECT * FROM students WHERE id=?',sid);if(!s||!s.id.startsWith(prefix[p.unit])||s.status!=='approved')fail('Matricule apenas alunos aprovados neste núcleo.',403)}id=id||randomUUID();run('INSERT INTO class_groups VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET label=excluded.label,weekdays=excluded.weekdays,start_time=excluded.start_time,end_time=excluded.end_time,active=excluded.active,version=excluded.version',id,p.unit,p.label.trim(),JSON.stringify(p.weekdays),p.start_time,p.end_time,Number(p.active),p.version+1);run('DELETE FROM group_students WHERE group_id=?',id);for(const sid of p.students)run('INSERT INTO group_students VALUES(?,?)',id,sid);audit(actor,'group.save:'+id);return read(actor,id)})},
  snapshotGroup(id,gid){run("INSERT INTO class_students SELECT ?,gs.student_id FROM group_students gs JOIN students s ON s.id=gs.student_id WHERE gs.group_id=? AND s.status='approved'",id,gid)}
 };
}
