import test from 'node:test';
import assert from 'node:assert/strict';
import {csv,parseCsv,validateStudent,signPreview,readPreview,fileType} from './portal-domain.mjs';
import {handlePortal} from './portal-handler.mjs';
const pupil={id:'UND1_000002',name:'Aluno Fictício',birth_date:'2014-05-12',status:'approved',height_cm:null,weight_kg:null,kimono:'',rashguard:'',shorts:'',version:1};
const env={PORTAL_DATA_DIR:'local-test-only',PORTAL_SECRET:'test-secret-'.repeat(4)};
function mock(role='guardian',links=['UND1_000002']){const writes=[];return {writes,user:async()=>({id:'11111111-1111-4111-8111-111111111111'}),member:async()=>({role,email:'fake@example.test',active:true}),links:async()=>links.map(student_id=>({student_id})),student:async()=>pupil,students:async()=>[pupil],update:async(a,r)=>writes.push(r),import:async(a,r)=>writes.push(...r),audit:async()=>{},documents:async()=>[{id:'22222222-2222-4222-8222-222222222222',kind:'student_document',object_path:'private/path',student_id:pupil.id}],document:async()=>({kind:'student_document',student_id:pupil.id}),members:async()=>[]}}
function req(path,method='GET',data,extra={}){return new Request('https://project.test/api/portal'+path,{method,headers:{Origin:'https://project.test',Authorization:'Bearer '+'a'.repeat(32),...(data?{'Content-Type':'application/json'}:{}),...extra},...(data?{body:JSON.stringify(data)}:{})})}
test('CSV preserva acentos, vírgulas e aspas; medidas opcionais',()=>{const input={...pupil,name:'Aluno "Exemplo", Fictício'};assert.deepEqual(parseCsv(csv([input])),[input])});
test('CSV rejeita duplicata, formato errado, coluna desconhecida e data inválida',()=>{assert.throws(()=>parseCsv(csv([pupil,pupil])));assert.throws(()=>parseCsv('id,name\na,b'));assert.throws(()=>validateStudent({...pupil,birth_date:'2014-02-30'}));assert.throws(()=>validateStudent({...pupil,role:'admin'}));assert.throws(()=>parseCsv(csv([pupil]).replace('"name"','"admin"')))});
test('CSV neutraliza fórmulas exportadas',()=>{assert.match(csv([{name:'=1+1'}],['name']),/'=1\+1/);assert.match(csv([{name:' @SUM(A1)'}],['name']),/' @SUM/)});
test('prévia rejeita alteração, outro ator, expiração e partes extras',()=>{const key='secret',t=signPreview({actor:'a',rows:[pupil],expires:Date.now()+10000},key);assert.equal(readPreview(t,key,'a')[0].id,pupil.id);assert.throws(()=>readPreview(t+'x',key,'a'));assert.throws(()=>readPreview(t,key,'b'));assert.throws(()=>readPreview(t+'.x',key,'a'));assert.throws(()=>readPreview(signPreview({actor:'a',rows:[],expires:0},key),key,'a'))});
test('assinatura de arquivo rejeita HTML disfarçado',()=>{assert.throws(()=>fileType(Buffer.from('<html>')));assert.equal(fileType(Buffer.from('%PDF-1.7'))[0],'application/pdf')});
test('desconfigurado fecha acesso e não expõe cadastro',async()=>{const r=await handlePortal(req('/students'),{});assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/Aluno Fictício/)});
test('sem token ou origem correta não altera nada',async()=>{const s=mock();assert.equal((await handlePortal(req('/students','GET',null,{Authorization:''}),env,s)).status,401);assert.equal((await handlePortal(req('/students/'+pupil.id,'PATCH',{weight_kg:20,version:1},{Origin:'https://evil.test'}),env,s)).status,403);assert.equal(s.writes.length,0)});
test('responsável sem vínculo não vê nem altera outro aluno',async()=>{const s=mock('guardian',[]);assert.equal((await handlePortal(req('/students/'+pupil.id),env,s)).status,403);assert.equal((await handlePortal(req('/students/'+pupil.id,'PATCH',{weight_kg:20,version:1}),env,s)).status,403);assert.deepEqual((await (await handlePortal(req('/students'),env,s)).json()).students,[])});
test('responsável vinculado atualiza medidas mas não aprovação ou nome',async()=>{const s=mock();assert.equal((await handlePortal(req('/students/'+pupil.id,'PATCH',{weight_kg:20,version:1}),env,s)).status,200);assert.equal(s.writes[0].weight_kg,20);assert.equal((await handlePortal(req('/students/'+pupil.id,'PATCH',{name:'Outro Aluno',version:1}),env,s)).status,403);assert.equal((await handlePortal(req('/students/'+pupil.id,'PATCH',{status:'approved',version:1}),env,s)).status,403)});
test('profissional não edita ficha nem baixa identidade',async()=>{const s=mock('psychologist');assert.equal((await handlePortal(req('/students/'+pupil.id,'PATCH',{version:1,weight_kg:20}),env,s)).status,403);assert.equal((await handlePortal(req('/students/'+pupil.id+'/documents'),env,s)).status,403);assert.equal((await handlePortal(req('/documents/22222222-2222-4222-8222-222222222222/download'),env,s)).status,403)});
test('responsável não importa ou concede papel de equipe',async()=>{for(const role of ['guardian']){const s=mock(role);assert.equal((await handlePortal(req('/import/preview','POST',{csv:csv([pupil])}),env,s)).status,403);assert.equal((await handlePortal(req('/members','POST',{email:'example@example.test',role:'admin'}),env,s)).status,403)}});
test('admin prévia não grava e confirmação usa lote validado',async()=>{const s=mock('admin');const r=await handlePortal(req('/import/preview','POST',{csv:csv([pupil])}),env,s);assert.equal(r.status,200);assert.equal(s.writes.length,0);const {token}=await r.json();assert.equal((await handlePortal(req('/import/commit','POST',{token}),env,s)).status,200);assert.equal(s.writes.length,1)});
test('admin rejeita versão desatualizada antes de prévia',async()=>{const s=mock('admin');assert.equal((await handlePortal(req('/import/preview','POST',{csv:csv([{...pupil,version:0}])}),env,s)).status,409);assert.equal(s.writes.length,0)});
test('CSV administrativo não cria ID manual, inclusive com prévia antiga assinada',async()=>{const s=mock('admin'),rows=[{...pupil,id:'UND1_999999',version:0}];assert.equal((await handlePortal(req('/import/preview','POST',{csv:csv(rows)}),env,s)).status,400);const token=signPreview({actor:'11111111-1111-4111-8111-111111111111',rows,expires:Date.now()+60000},env.PORTAL_SECRET);assert.equal((await handlePortal(req('/import/commit','POST',{token}),env,s)).status,400);assert.equal(s.writes.length,0)});
test('arquivos não revelam caminho privado na listagem',async()=>{const r=await handlePortal(req('/students/'+pupil.id+'/documents'),env,mock());assert.equal(r.status,200);assert.doesNotMatch(await r.text(),/object_path|private\/path/)});
