import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {JSDOM,VirtualConsole} from 'jsdom';
const settle=()=>new Promise(r=>setTimeout(r,20));
function ui(t,api,module){
 const errors=[],messages=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM('<main id="area"></main>',{url:'https://example.test',runScripts:'outside-only',virtualConsole:vc}),w=dom.window;
 t.after(()=>{dom.window.close();assert.deepEqual(errors,[])});w.HTMLElement.prototype.scrollIntoView=()=>{};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};
 vm.runInContext(fs.readFileSync(new URL('./dist/portal/action.js',import.meta.url),'utf8'),dom.getInternalVMContext());
 vm.runInContext(`function el(tag,text,attrs={}){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;for(const [k,v] of Object.entries(attrs))e.setAttribute(k,v);return e}
 function field(parent,label,name,value,attrs={}){const wrap=el('label',label),e=el(attrs.options?'select':'input',undefined,{name});if(attrs.options){for(const [v,l]of Object.entries(attrs.options))e.append(el('option',l,{value:v}))}for(const [k,v]of Object.entries(attrs))if(k!=='options')e.setAttribute(k,v);if(attrs.type!=='file')e.value=value;wrap.append(e);parent.append(wrap);return e}`,dom.getInternalVMContext());
 w.api=api;w.notice=(msg,error)=>messages.push({msg,error});vm.runInContext(fs.readFileSync(new URL('./dist/portal/'+module,import.meta.url),'utf8').replace('export async function','async function'),dom.getInternalVMContext());
 return {w,messages,root:w.document.getElementById('area'),async mount(name){return vm.runInContext(`${name}({api,el,field,notice,action:createPortalAction({notice,el}),onSaved:async()=>{}},document.getElementById('area'),'lesson-id')`,dom.getInternalVMContext())}};
}
test('Interface do limite: salva somente após prévia e invalida prévia ao mudar o valor',async t=>{
 const calls=[],api=async(route,p)=>{calls.push({route,...p});if(route.endsWith('/preview'))return {before:3,after:p.data.threshold,preview_token:'preview',impact:{active_before:1,active_after:0},message:'Prévia de teste'};if(p?.method==='PATCH')return {settings:{},message:'Salvo'};return {settings:{can_edit:true,threshold:3,version:1,history:[]}}};
 const u=ui(t,api,'absence-settings.js');await u.mount('mountAbsenceSettings');u.root.querySelector('details').open=true;await settle();const input=u.root.querySelector('[name=threshold]'),buttons=u.root.querySelectorAll('form button');assert.equal(buttons[1].disabled,true);input.value=5;input.dispatchEvent(new u.w.Event('input'));buttons[0].click();await settle();assert.equal(buttons[1].disabled,false);assert.match(u.root.textContent,/1 → 0/);input.value=4;input.dispatchEvent(new u.w.Event('input'));assert.equal(buttons[1].disabled,true);buttons[0].click();await settle();u.root.querySelector('[name=reason]').value='Motivo fictício';u.root.querySelector('form').dispatchEvent(new u.w.Event('submit',{cancelable:true}));await settle();const save=calls.find(c=>c.method==='PATCH');assert.equal(save.data.threshold,4);assert.equal(save.data.preview_token,'preview');assert.equal(save.data.reason,'Motivo fictício');
});
test('Interface da foto: falha preserva arquivo e repetição usa o mesmo identificador',async t=>{
 const calls=[];let fail=true;const api=async(route,p)=>{if(p?.method==='POST'){calls.push(p.form);if(fail)throw Error('Falha simulada de conexão');return {message:'Foto recebida'}}return {lesson:{cancelled:false},check:{status:'empty',version:0},photos:[],history:[],can_review:false}};
 const u=ui(t,api,'class-evidence.js');await u.mount('mountClassEvidence');assert.equal(u.root.querySelector('[name=camera]').getAttribute('capture'),'environment');const input=u.root.querySelector('[name=file]');Object.defineProperty(input,'files',{value:[new u.w.File(['fake'],'test.png',{type:'image/png'})]});input.dispatchEvent(new u.w.Event('change'));const form=input.form;form.dispatchEvent(new u.w.Event('submit',{cancelable:true}));await settle();assert.match(form.textContent,/Falha simulada/);assert.equal(input.files.length,1);fail=false;form.dispatchEvent(new u.w.Event('submit',{cancelable:true}));await settle();assert.equal(calls.length,2);assert.equal(calls[0].get('request_id'),calls[1].get('request_id'));assert.equal(calls[0].get('version'),'0');assert.ok(u.messages.some(m=>m.msg==='Foto recebida'));
});
test('Interface da foto: decisão inclui versão e fotografia vistas; professor não recebe revisão',async t=>{
 const posted=[];let manager=true;const api=async(route,p)=>{if(p?.blob)return new Blob(['image']);if(p?.method==='POST'){posted.push(p.data);return {message:'Conferido'}}return {lesson:{cancelled:false},check:{status:'pending',version:7,attendance_fingerprint:'snapshot'},photos:[{id:'photo-id',created_at:'2026-10-01T12:00:00Z',caption:'Fictícia'}],history:[],can_review:manager}};
 const u=ui(t,api,'class-evidence.js');await u.mount('mountClassEvidence');let review=u.root.querySelector('[name=decision]').form;review.dispatchEvent(new u.w.Event('submit',{cancelable:true}));await settle();assert.equal(posted[0].attendance_fingerprint,'snapshot');assert.equal(posted[0].version,7);manager=false;u.root.replaceChildren();await u.mount('mountClassEvidence');assert.equal(u.root.querySelector('[name=decision]'),null);
});


test('Interface da foto: ausência de arquivo mostra erro junto ao formulário, preserva legenda e não envia',async t=>{
 const sent=[];const api=async(route,p)=>{if(p?.method==='POST')sent.push(p);return {lesson:{cancelled:false},check:{status:'empty',version:0},photos:[],history:[],can_review:false}};
 const u=ui(t,api,'class-evidence.js');await u.mount('mountClassEvidence');const form=u.root.querySelector('form'),caption=form.querySelector('[name=caption]');caption.value='Legenda preservada';form.dispatchEvent(new u.w.Event('submit',{cancelable:true}));await settle();const feedback=form.querySelector('[role=alert]');assert.ok(feedback);assert.match(feedback.textContent,/Escolha uma foto/);assert.equal(caption.value,'Legenda preservada');assert.equal(sent.length,0);assert.equal(form.querySelector('button').disabled,false);assert.equal(u.w.document.activeElement,feedback);
});
