import {fixtureTeacher,fixtureGroup} from './school-fixtures.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {createSqliteStore} from './portal-sqlite.mjs';
import {handlePortal} from './portal-handler.mjs';
import {validCpf} from './professional-tools.mjs';
const tomorrow=new Date(Date.now()+2*86400000).toISOString().slice(0,10),until=new Date(Date.now()+200*86400000).toISOString().slice(0,10);
async function fixture(t){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lpc-prof-')),mail=[],env={PORTAL_DATA_DIR:dir,PORTAL_SECRET:'private-test-'.repeat(4),BOOTSTRAP_ADMIN_EMAIL:'admin@example.test',RESEND_API_KEY:'fake',MAIL_FROM:'test@example.test',PUBLIC_ORIGIN:'https://example.test'};
 const store=createSqliteStore(env,{transport:async(u,o)=>{mail.push(JSON.parse(o.body));return Response.json({id:'test'})}}),admin=(await store.members())[0];
 t.after(()=>{store.close();assert.ok(dir.startsWith(path.join(os.tmpdir(),'lpc-prof-')));fs.rmSync(dir,{recursive:true,force:true})});
 const login=async email=>{await store.requestCode(email);return (await store.verifyCode(email,mail.at(-1).text.match(/\b\d{8}\b/)[0])).access_token};
 const token=await login(admin.email),request=(route,{method='GET',data,form,auth=token}={})=>handlePortal(new Request(env.PUBLIC_ORIGIN+'/api/portal'+route,{method,headers:{origin:env.PUBLIC_ORIGIN,Authorization:'Bearer '+auth,...(data?{'Content-Type':'application/json'}:{})},body:form||(data?JSON.stringify(data):undefined)}),env,store);
 await store.import(admin.user_id,[{id:'UND1_000001',name:'Aluno Fictício Um',birth_date:'2015-02-01',status:'approved',version:0},{id:'UND1_000002',name:'Aluno Fictício Dois',birth_date:'2018-04-01',status:'approved',version:0},{id:'UND2_000001',name:'Aluno Outro Núcleo',birth_date:'2017-03-01',status:'approved',version:0}]);
 const profile={name:'Profissional Fictício',email:'professional@example.test',role:'psychologist',phone:'21999999999',rg:'TESTE123',cpf:'52998224725',council_number:'TESTE-000',council_region:'RJ',review_until:until,status:'pending',version:0,units:['amavale']};
 async function professional(role='psychologist',email=profile.email){let p=await store.saveProfessional(admin.user_id,null,{...profile,role,email});for(const kind of ['photo','council']){await store.addProfessionalDocument(admin.user_id,p.user_id,{id:randomUUID(),kind,object_path:'tests/'+randomUUID()+'.pdf',mime:kind==='photo'?'image/png':'application/pdf',size:24,original_name:'fake'});}p=await store.professional(admin.user_id,p.user_id);const saved=await store.saveProfessional(admin.user_id,p.user_id,{...profile,role,email,status:'verified',version:p.version,checked:true});return saved}
 async function guardian(email='guardian@example.test',sid='UND1_000001'){const g=await store.provision(email,'guardian');await store.link(admin.user_id,g.user_id,sid);return g}
 const slot=(uid,time='10:00',end='10:50')=>store.createSlot(admin.user_id,{professional_id:uid,unit:'amavale',day:tomorrow,start_time:time,end_time:end});
 const booking=(slot,id='UND1_000001')=>({id:randomUUID(),student_id:id,contact_name:'Responsável Fictício',phone:'21999999999',consent:true,version:slot.version});
 return {store,admin,request,login,profile,professional,guardian,slot,booking,mail};
}
test('Profissionais: cadastro privado, CPF, documentos e conferência antes de ofertar horários',async t=>{const f=await fixture(t),{store,admin}=f;assert.equal(validCpf('11111111111'),false);assert.equal(validCpf('52998224725'),true);await assert.rejects(store.saveProfessional(admin.user_id,null,{...f.profile,cpf:'12345678901'}));const p=await store.saveProfessional(admin.user_id,null,f.profile);await assert.rejects(f.slot(p.user_id),{status:403});await assert.rejects(store.saveProfessional(admin.user_id,p.user_id,{...f.profile,status:'verified',version:1,checked:true}));const g=await f.guardian();await assert.rejects(store.professional(g.user_id,p.user_id),{status:403});const sec=await store.provision('secretary@example.test','secretary');assert.equal((await store.professional(sec.user_id,p.user_id)).cpf,f.profile.cpf);const list=await store.professionals(sec.user_id);assert.equal(list[0].cpf,undefined);assert.equal(list[0].rg,undefined)});
test('Profissionais: arquivos privados, upload válido e impedimento de consulta cruzada',async t=>{const f=await fixture(t),p=await f.professional(),other=await f.professional('social_worker','other@example.test'),auth=await f.login(other.email);assert.equal((await f.request('/professionals/'+p.user_id,{auth})).status,403);const data=new FormData();data.set('kind','council');data.set('file',new Blob(['%PDF-1.7\nfictitious\n%%EOF'],{type:'application/pdf'}),'conselho.pdf');const r=await f.request('/professionals/'+p.user_id+'/documents',{method:'POST',form:data});assert.equal(r.status,201);const id=(await r.json()).id;assert.equal((await f.request('/professional-documents/'+id+'/download',{auth})).status,403);assert.equal((await f.request('/professional-documents/'+id+'/download')).status,200);assert.equal((await f.store.professional(f.admin.user_id,p.user_id)).available,false);await assert.rejects(f.slot(p.user_id),{status:403})});
test('Agenda: sobreposição bloqueada, datas inválidas e acesso por profissional',async t=>{const f=await fixture(t),p=await f.professional(),other=await f.professional('social_worker','other@example.test');const s=await f.slot(p.user_id);await assert.rejects(f.slot(p.user_id,'10:20','11:00'),{status:409});await f.slot(p.user_id,'10:50','11:30');await assert.rejects(f.store.createSlot(other.user_id,{professional_id:p.user_id,unit:'amavale',day:tomorrow,start_time:'15:00',end_time:'16:00'}),{status:403});await assert.rejects(f.store.createSlot(p.user_id,{professional_id:p.user_id,unit:'amavale',day:'2026-02-30',start_time:'12:00',end_time:'13:00'}));await assert.rejects(f.store.cancelSlot(other.user_id,s.id,s.version),{status:403})});
test('Agenda: reserva atômica, idempotência, vínculo obrigatório e atendimento em outro núcleo',async t=>{const f=await fixture(t),p=await f.professional(),g=await f.guardian(),g2=await f.guardian('guardian2@example.test','UND1_000002'),s=await f.slot(p.user_id),payload=f.booking(s);const results=await Promise.allSettled([f.store.bookSlot(g.user_id,s.id,payload),f.store.bookSlot(g2.user_id,s.id,f.booking(s,'UND1_000002'))]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results[1].reason.status,409);const replay=await f.store.bookSlot(g.user_id,s.id,payload);assert.equal(replay.id,payload.id);assert.equal((await f.store.availableSlots(g.user_id,'UND1_000001')).length,0);await assert.rejects(f.store.availableSlots(g.user_id,'UND1_000002'),{status:403});const s2=await f.slot(p.user_id,'12:00','12:50');await assert.rejects(f.store.bookSlot(g.user_id,s2.id,f.booking(s2,'UND1_000002')),{status:403});assert.equal((await f.store.availableSlots(g.user_id,'UND1_000001'))[0].cpf,undefined);const cross=await f.store.bookSlot(f.admin.user_id,s2.id,f.booking(s2,'UND2_000001'));assert.equal(cross.unit,'amavale');assert.equal((await f.store.student('UND2_000001')).id,'UND2_000001');assert.equal((await f.store.bookings(g2.user_id)).length,0)});
test('Agenda: confirmação somente pela equipe após WhatsApp; cancelamento libera vaga',async t=>{const f=await fixture(t),p=await f.professional(),g=await f.guardian(),s=await f.slot(p.user_id),b=await f.store.bookSlot(g.user_id,s.id,f.booking(s));const update={status:'confirmed',version:b.version,reason:'Família contatada',contacted:true};await assert.rejects(f.store.reviewBooking(g.user_id,b.id,update),{status:403});await assert.rejects(f.store.reviewBooking(p.user_id,b.id,update),{status:403});await assert.rejects(f.store.reviewBooking(f.admin.user_id,b.id,{...update,contacted:false}));const confirmed=await f.store.reviewBooking(f.admin.user_id,b.id,update);await assert.rejects(f.store.reviewBooking(f.admin.user_id,b.id,update),{status:409});await assert.rejects(f.store.cancelSlot(p.user_id,s.id,s.version),{status:409});await assert.rejects(f.store.reviewBooking(f.admin.user_id,b.id,{status:'completed',reason:'Finalizado',version:confirmed.version}));await f.store.reviewBooking(f.admin.user_id,b.id,{status:'cancelled',reason:'Família solicitou cancelamento',version:confirmed.version});assert.equal((await f.store.availableSlots(g.user_id,'UND1_000001')).length,1)});
test('Agenda: integração HTTP, aviso mínimo por email e isolamento de outra conta',async t=>{const f=await fixture(t),p=await f.professional(),g=await f.guardian(),s=await f.slot(p.user_id),auth=await f.login(g.email),data=f.booking(s);const r=await f.request('/slots/'+s.id+'/book',{method:'POST',data,auth});assert.equal(r.status,201);const mail=f.mail.at(-1);assert.ok(mail.to.includes(p.email));assert.ok(!mail.text.includes('Aluno Fictício'));const count=f.mail.length;assert.equal((await f.request('/slots/'+s.id+'/book',{method:'POST',data,auth})).status,201);assert.equal(f.mail.length,count);assert.equal((await f.request('/bookings.csv',{auth})).status,403);const before=await f.store.bookings(g.user_id);assert.equal(before.length,1);await f.store.setMember(f.admin.user_id,p.user_id,p.role,false);assert.equal((await f.store.professionals(f.admin.user_id))[0].available,false);assert.equal((await f.store.bookings(g.user_id))[0].id,before[0].id)});
test('Turmas: matrícula por horário, snapshot da chamada e autorização para presença',async t=>{const f=await fixture(t),{store,admin}=f;const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10),day=new Date(yesterday+'T12:00:00Z').getUTCDay(),responsible=await fixtureTeacher(store,admin.user_id),payload={teachers:[responsible.user_id],unit:'amavale',label:'Infantil fictício',weekdays:[day],start_time:'16:25',end_time:'17:00',active:true,version:0,students:['UND1_000002']};const group=await store.saveGroup(admin.user_id,null,payload);const lesson=await store.createClass(admin.user_id,{group_id:group.id,day:yesterday,unit:'valparaiso',time:'00:00',label:'spoof'});assert.equal(lesson.unit,'amavale');assert.equal(lesson.time,'16:25');const roster=await store.attendance(admin.user_id,lesson.id);assert.deepEqual(roster.students.map(s=>s.id),['UND1_000002']);await assert.rejects(store.markAttendance(admin.user_id,lesson.id,[{id:'UND1_000001',status:'present',version:0}]),{status:403});await store.markAttendance(admin.user_id,lesson.id,[{id:'UND1_000002',status:'present',version:0}]);await assert.rejects(store.markAttendance(admin.user_id,lesson.id,[{id:'UND1_000002',status:'absent',version:0}]),{status:409});await store.saveGroup(admin.user_id,group.id,{...payload,version:1,students:[]});assert.equal((await store.attendance(admin.user_id,lesson.id)).students.length,1);await assert.rejects(store.saveGroup(admin.user_id,group.id,{...payload,version:2,students:['UND2_000001']}),{status:403});const g=await f.guardian();await assert.rejects(store.saveGroup(g.user_id,null,payload),{status:403})});
test('Relatos: campos de ocorrência e lesão preservados, exportados e protegidos',async t=>{const f=await fixture(t),id=randomUUID(),details={location:'Sala de treino',teacher_present:'Professor Fictício',activity:'Queda observada',symptoms:'Relato fictício',emergency_called:'Não',declarant:'Professor Fictício',care_instructions:'Referência do atendimento'};await f.store.createReport(f.admin.user_id,{id,kind:'injury',unit:'amavale',student_id:'UND1_000002',occurred_at:'2025-01-01T15:30',category:'Braço',description:'Dados fictícios para verificar registro',actions:'Procedimentos registrados no teste',guardian_contact:'Responsável avisado',referral:'Não houve neste teste',details});assert.deepEqual((await f.store.report(f.admin.user_id,id)).details,details);const rows=await f.store.reportsExport(f.admin.user_id,'amavale');assert.deepEqual(JSON.parse(rows[0].details_json),details);const g=await f.guardian();await assert.rejects(f.store.report(g.user_id,id),{status:403})});
