import {randomUUID} from 'node:crypto';
import {fail} from './portal-domain.mjs';
const units=['amavale','valparaiso','vale-do-carangola'];
const prefix={amavale:'UND1_',valparaiso:'UND2_','vale-do-carangola':'UND3_'};
function date(v){if(typeof v!=='string'||!/^20\d{2}-\d{2}-\d{2}$/.test(v))fail('Confira a data.');const d=new Date(v+'T12:00:00Z');if(!Number.isFinite(+d)||d.toISOString().slice(0,10)!==v)fail('Confira a data.');return v}
export function projectTools({db,get,all,run,tx,requireRole,audit,requireUnit}){
 db.exec(`CREATE TABLE IF NOT EXISTS student_contacts(student_id TEXT PRIMARY KEY REFERENCES students(id),guardian_name TEXT NOT NULL,guardian_email TEXT NOT NULL,guardian_phone TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS classes(id TEXT PRIMARY KEY,unit TEXT NOT NULL,day TEXT NOT NULL,time TEXT NOT NULL,label TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES members(user_id),created_at TEXT NOT NULL,UNIQUE(unit,day,time,label));
 CREATE TABLE IF NOT EXISTS attendance(class_id TEXT NOT NULL REFERENCES classes(id),student_id TEXT NOT NULL REFERENCES students(id),status TEXT NOT NULL CHECK(status IN ('present','absent','justified','unmarked')),version INTEGER NOT NULL,updated_by TEXT NOT NULL REFERENCES members(user_id),updated_at TEXT NOT NULL,PRIMARY KEY(class_id,student_id));`);
 const api={
  approvedContact(r,actor){
   run('INSERT INTO student_contacts(student_id,guardian_name,guardian_email,guardian_phone) VALUES(?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET guardian_name=excluded.guardian_name,guardian_email=excluded.guardian_email,guardian_phone=excluded.guardian_phone',r.student_id,r.guardian_name,r.guardian_email.toLowerCase(),r.guardian_phone);
   const email=r.guardian_email.trim().toLowerCase();let m=get('SELECT * FROM members WHERE email=?',email);
   if(!m){m={user_id:randomUUID(),role:'guardian',active:1};run("INSERT INTO members(user_id,email,role) VALUES(?,?,'guardian')",m.user_id,email);audit(actor,'member.provision:'+m.user_id)}
   if(m.role==='guardian'&&m.active){run('INSERT OR IGNORE INTO links(user_id,student_id) VALUES(?,?)',m.user_id,r.student_id);audit(actor,'member.link:'+m.user_id,r.student_id)}
  },
  async appointmentContext(actor,id){const m=requireRole(actor,['admin','secretary','guardian']);if(m.role==='guardian'&&!get('SELECT 1 FROM links WHERE user_id=? AND student_id=?',actor,id))fail('Acesso não permitido.',403);const student=get("SELECT * FROM students WHERE id=? AND status='approved'",id);if(!student)fail('Cadastro sem aprovação ativa.',403);return {student,contact:get('SELECT guardian_name,guardian_phone FROM student_contacts WHERE student_id=?',id)||{guardian_name:'',guardian_phone:''}}},
  async classes(actor,unit){requireUnit(actor,unit);if(!units.includes(unit))fail('Núcleo inválido.');return all('SELECT * FROM classes WHERE unit=? ORDER BY day DESC,time DESC LIMIT 100',unit)},
  async createClass(actor,p){return tx(()=>{requireUnit(actor,p.unit);if(!units.includes(p.unit)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(p.time)||typeof p.label!=='string'||p.label.trim().length<3||p.label.length>100||/[\x00-\x1f]/.test(p.label))fail('Confira núcleo, horário e nome da aula.');date(p.day);const old=get('SELECT * FROM classes WHERE unit=? AND day=? AND time=? AND label=?',p.unit,p.day,p.time,p.label.trim());if(old)return old;const id=randomUUID();run('INSERT INTO classes VALUES(?,?,?,?,?,?,?)',id,p.unit,p.day,p.time,p.label.trim(),actor,new Date().toISOString());audit(actor,'class.create:'+id);return get('SELECT * FROM classes WHERE id=?',id)})},
  async attendance(actor,id){requireRole(actor,['admin','secretary','teacher']);const lesson=get('SELECT * FROM classes WHERE id=?',id);if(!lesson)fail('Aula não localizada.',404);requireUnit(actor,lesson.unit);const students=all("SELECT s.id,s.name,COALESCE(a.status,'unmarked') AS status,COALESCE(a.version,0) AS version FROM students s LEFT JOIN attendance a ON a.student_id=s.id AND a.class_id=? WHERE substr(s.id,1,5)=? AND (s.status='approved' OR a.class_id IS NOT NULL) ORDER BY s.name,s.id",id,prefix[lesson.unit]);return {lesson,students}},
  async markAttendance(actor,id,rows){return tx(()=>{requireRole(actor,['admin','secretary','teacher']);const lesson=get('SELECT * FROM classes WHERE id=?',id);if(!lesson)fail('Aula não localizada.',404);requireUnit(actor,lesson.unit);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());if(lesson.day>today)fail('Registre a chamada na data da aula ou depois.');if(!Array.isArray(rows)||!rows.length||rows.length>500)fail('Chamada inválida.');const seen=new Set();for(const r of rows){if(!r||typeof r.id!=='string'||seen.has(r.id)||!['present','absent','justified','unmarked'].includes(r.status)||!Number.isSafeInteger(r.version)||r.version<0)fail('Chamada inválida.');seen.add(r.id);const s=get('SELECT * FROM students WHERE id=?',r.id),old=get('SELECT * FROM attendance WHERE class_id=? AND student_id=?',id,r.id);if(!s||!s.id.startsWith(prefix[lesson.unit])||s.status!=='approved'&&!old)fail('Aluno não pertence à lista desta aula.',403);if((old?.version||0)!==r.version)fail('A chamada foi alterada. Recarregue antes de salvar.',409);run('INSERT INTO attendance VALUES(?,?,?,?,?,?) ON CONFLICT(class_id,student_id) DO UPDATE SET status=excluded.status,version=excluded.version,updated_by=excluded.updated_by,updated_at=excluded.updated_at',id,r.id,r.status,r.version+1,actor,new Date().toISOString());audit(actor,'attendance.'+r.status+':'+id,r.id)}return rows.length})},
  async attendanceExport(actor,unit,from,to){requireUnit(actor,unit);date(from);date(to);if(!units.includes(unit)||from>to||(new Date(to)-new Date(from))/86400000>366)fail('Selecione núcleo e período de até um ano.');audit(actor,'attendance.export');return all('SELECT c.day AS date,c.time,c.label AS class,c.unit,s.id AS student_id,s.name,a.status,a.version,a.updated_at FROM attendance a JOIN classes c ON c.id=a.class_id JOIN students s ON s.id=a.student_id WHERE c.unit=? AND c.day BETWEEN ? AND ? ORDER BY c.day,c.time,s.name',unit,from,to)}
 };return api;
}
