import {attendanceHistory} from './attendance-history.mjs';
import {classGroups} from './class-groups.mjs';
import {randomUUID} from 'node:crypto';
import {fail} from './portal-domain.mjs';
const units=['amavale','valparaiso','vale-do-carangola'];
const prefix={amavale:'UND1_',valparaiso:'UND2_','vale-do-carangola':'UND3_'};
function date(v){if(typeof v!=='string'||!/^20\d{2}-\d{2}-\d{2}$/.test(v))fail('Confira a data.');const d=new Date(v+'T12:00:00Z');if(!Number.isFinite(+d)||d.toISOString().slice(0,10)!==v)fail('Confira a data.');return v}
export function projectTools({db,get,all,run,tx,requireRole,audit,requireUnit,onAttendanceChanged=()=>{}}){
 db.exec(`CREATE TABLE IF NOT EXISTS student_contacts(student_id TEXT PRIMARY KEY REFERENCES students(id),guardian_name TEXT NOT NULL,guardian_email TEXT NOT NULL,guardian_phone TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS classes(id TEXT PRIMARY KEY,unit TEXT NOT NULL,day TEXT NOT NULL,time TEXT NOT NULL,label TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES members(user_id),created_at TEXT NOT NULL,UNIQUE(unit,day,time,label));
 CREATE TABLE IF NOT EXISTS attendance(class_id TEXT NOT NULL REFERENCES classes(id),student_id TEXT NOT NULL REFERENCES students(id),status TEXT NOT NULL CHECK(status IN ('present','absent','justified','unmarked')),version INTEGER NOT NULL,updated_by TEXT NOT NULL REFERENCES members(user_id),updated_at TEXT NOT NULL,PRIMARY KEY(class_id,student_id));`);
 const groups=classGroups({db,get,all,run,tx,requireRole,requireUnit,audit});
 for(const [name,type]of [['cancelled','INTEGER NOT NULL DEFAULT 0'],['cancellation_reason',"TEXT NOT NULL DEFAULT ''"]])if(!all('PRAGMA table_info(classes)').some(c=>c.name===name))db.exec('ALTER TABLE classes ADD COLUMN '+name+' '+type);
 function lessonAccess(actor,lesson){const m=requireRole(actor,['admin','secretary','teacher']);requireUnit(actor,lesson.unit);if(m.role==='teacher'){if(!lesson.group_id)fail('Use uma turma vinculada ao seu cadastro.',403);groups.groupRead(actor,lesson.group_id)}}
 const history=attendanceHistory({db,get,all,run,requireRole,lessonAccess});
 function attendanceAuthority(actor){const m=requireRole(actor,['admin','secretary','teacher']);return {can_write_attendance:m.role==='admin'||m.role==='teacher'||get("SELECT 1 FROM administrative_profiles WHERE user_id=? AND secretary_level='general'",actor)!==undefined,secretary_level:m.role==='secretary'?(get('SELECT secretary_level FROM administrative_profiles WHERE user_id=?',actor)?.secretary_level||'local'):null}}
 function requireAttendanceWrite(actor,lesson){lessonAccess(actor,lesson);if(!attendanceAuthority(actor).can_write_attendance)fail('Somente o professor vinculado à turma, administradores e secretaria geral podem lançar ou alterar a chamada.',403);}
 function canAttendanceWrite(actor,lesson){try{requireAttendanceWrite(actor,lesson);return true}catch(e){if(e.status===403)return false;throw e}}
 const api={...groups,...history,lessonAccess,requireAttendanceWrite,canAttendanceWrite,async attendanceAuthority(actor){return attendanceAuthority(actor)},
  approvedContact(r,actor){
   run('INSERT INTO student_contacts(student_id,guardian_name,guardian_email,guardian_phone) VALUES(?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET guardian_name=excluded.guardian_name,guardian_email=excluded.guardian_email,guardian_phone=excluded.guardian_phone',r.student_id,r.guardian_name,r.guardian_email.toLowerCase(),r.guardian_phone);
   const email=r.guardian_email.trim().toLowerCase();let m=get('SELECT * FROM members WHERE email=?',email);
   if(!m){m={user_id:randomUUID(),role:'guardian',active:1};run("INSERT INTO members(user_id,email,role) VALUES(?,?,'guardian')",m.user_id,email);audit(actor,'member.provision:'+m.user_id)}
   run('UPDATE student_contacts SET relationship=?,version=version+1 WHERE student_id=?',r.relationship||'',r.student_id);
   if(m.role==='guardian'&&m.active){run('INSERT OR IGNORE INTO links(user_id,student_id) VALUES(?,?)',m.user_id,r.student_id);audit(actor,'member.link:'+m.user_id,r.student_id)}
  },
  async appointmentContext(actor,id){const m=requireRole(actor,['admin','secretary','guardian']);if(m.role==='guardian'&&!get('SELECT 1 FROM links WHERE user_id=? AND student_id=?',actor,id))fail('Acesso não permitido.',403);const student=get("SELECT * FROM students WHERE id=? AND status='approved'",id);if(!student)fail('Cadastro sem aprovação ativa.',403);return {student,contact:get('SELECT guardian_name,guardian_phone FROM student_contacts WHERE student_id=?',id)||{guardian_name:'',guardian_phone:''}}},
  async classes(actor,unit){const m=requireRole(actor,['admin','secretary','teacher']);requireUnit(actor,unit);return all('SELECT * FROM classes WHERE unit=? ORDER BY day DESC,time DESC LIMIT 100',unit).filter(c=>m.role!=='teacher'||c.group_id&&get('SELECT 1 FROM group_teachers WHERE group_id=? AND teacher_id=?',c.group_id,actor))},
  async createClass(actor,p){return tx(()=>{let group=null;if(requireRole(actor,['admin','secretary','teacher']).role==='teacher'&&!p.group_id)fail('Selecione uma turma vinculada ao professor.',403);if(!p.group_id)fail('Selecione uma turma com professor responsável.');if(p.group_id){group=groups.groupRead(actor,p.group_id);date(p.day);if(!group.active||!group.weekdays.includes(new Date(p.day+'T12:00:00Z').getUTCDay()))fail('A turma não tem aula neste dia.');p={...p,unit:group.unit,time:group.start_time,label:group.label}}requireAttendanceWrite(actor,{...p,group_id:group?.id});if(group&&!groups.eligibleGroupTeachers(group.id).length)fail('Esta turma está sem professor habilitado. Confira o vínculo antes de abrir a chamada.',409);requireUnit(actor,p.unit);if(!units.includes(p.unit)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(p.time)||typeof p.label!=='string'||p.label.trim().length<3||p.label.length>100||/[\x00-\x1f]/.test(p.label))fail('Confira núcleo, horário e nome da aula.');date(p.day);const old=group?get('SELECT * FROM classes WHERE group_id=? AND day=?',group.id,p.day):get('SELECT * FROM classes WHERE unit=? AND day=? AND time=? AND label=?',p.unit,p.day,p.time,p.label.trim());if(old)return old;const id=randomUUID();run('INSERT INTO classes(id,unit,day,time,label,created_by,created_at,group_id) VALUES(?,?,?,?,?,?,?,?)',id,p.unit,p.day,p.time,p.label.trim(),actor,new Date().toISOString(),group?.id||null);if(group)groups.snapshotGroup(id,group.id);audit(actor,'class.create:'+id);return get('SELECT * FROM classes WHERE id=?',id)})},
  async attendance(actor,id){requireRole(actor,['admin','secretary','teacher']);const lesson=get('SELECT * FROM classes WHERE id=?',id);if(!lesson)fail('Aula não localizada.',404);lessonAccess(actor,lesson);const students=all("SELECT s.id,s.name,COALESCE(a.status,'unmarked') AS status,COALESCE(a.version,0) AS version,a.updated_by,a.updated_at,COALESCE((SELECT h.actor_name FROM attendance_changes h WHERE h.class_id=a.class_id AND h.student_id=a.student_id AND h.version=a.version ORDER BY h.id DESC LIMIT 1),'') AS updated_by_name FROM students s LEFT JOIN attendance a ON a.student_id=s.id AND a.class_id=? WHERE substr(s.id,1,5)=? AND (s.status='approved' OR a.class_id IS NOT NULL) AND (? IS NULL OR EXISTS(SELECT 1 FROM class_students cs WHERE cs.class_id=? AND cs.student_id=s.id)) ORDER BY s.name,s.id",id,prefix[lesson.unit],lesson.group_id,id);return {lesson,students,can_write:canAttendanceWrite(actor,lesson)}},
  async markAttendance(actor,id,rows){return tx(()=>{requireRole(actor,['admin','secretary','teacher']);const lesson=get('SELECT * FROM classes WHERE id=?',id);if(!lesson)fail('Aula não localizada.',404);requireAttendanceWrite(actor,lesson);if(lesson.cancelled)fail('A aula está cancelada. Reabra antes de lançar presença.');const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());if(lesson.day>today)fail('Registre a chamada na data da aula ou depois.');if(!Array.isArray(rows)||!rows.length||rows.length>500)fail('Chamada inválida.');const seen=new Set();for(const r of rows){if(!r||typeof r.id!=='string'||seen.has(r.id)||!['present','absent','justified','unmarked'].includes(r.status)||!Number.isSafeInteger(r.version)||r.version<0)fail('Chamada inválida.');seen.add(r.id);const s=get('SELECT * FROM students WHERE id=?',r.id),old=get('SELECT * FROM attendance WHERE class_id=? AND student_id=?',id,r.id);if(!s||!s.id.startsWith(prefix[lesson.unit])||s.status!=='approved'&&!old||lesson.group_id&&!get('SELECT 1 FROM class_students WHERE class_id=? AND student_id=?',id,r.id))fail('Aluno não pertence à lista desta aula.',403);if((old?.version||0)!==r.version)fail('A chamada foi alterada. Recarregue antes de salvar.',409);if((old?.status||'unmarked')===r.status)continue;history.recordAttendanceChange(actor,lesson,r,old);run('INSERT INTO attendance VALUES(?,?,?,?,?,?) ON CONFLICT(class_id,student_id) DO UPDATE SET status=excluded.status,version=excluded.version,updated_by=excluded.updated_by,updated_at=excluded.updated_at',id,r.id,r.status,r.version+1,actor,new Date().toISOString());audit(actor,'attendance.'+r.status+':'+id,r.id)}onAttendanceChanged();return rows.length})},
  async attendanceExport(actor,unit,from,to){requireUnit(actor,unit);date(from);date(to);if(!units.includes(unit)||from>to||(new Date(to)-new Date(from))/86400000>366)fail('Selecione núcleo e período de até um ano.');audit(actor,'attendance.export');const teacher=requireRole(actor,['admin','secretary','teacher']).role==='teacher';return all("SELECT c.id AS class_id,c.group_id,c.day AS date,c.time,c.label AS class,c.unit,s.id AS student_id,s.name,a.status,a.version,a.updated_at,a.updated_by,COALESCE((SELECT h.actor_name FROM attendance_changes h WHERE h.class_id=a.class_id AND h.student_id=a.student_id AND h.version=a.version ORDER BY h.id DESC LIMIT 1),'') AS updated_by_name FROM attendance a JOIN classes c ON c.id=a.class_id JOIN students s ON s.id=a.student_id WHERE c.unit=? AND c.cancelled=0 AND c.day BETWEEN ? AND ? ORDER BY c.day,c.time,s.name",unit,from,to).filter(c=>!teacher||c.group_id&&get('SELECT 1 FROM group_teachers WHERE group_id=? AND teacher_id=?',c.group_id,actor))}
 };return api;
}
