import test from 'node:test';
import assert from 'node:assert/strict';
import {handleAgenda} from './agenda-handler.mjs';
const env={RESEND_API_KEY:'mock',MAIL_FROM:'test@example.invalid'};
const sample={studentId:'UND1_000002',service:'Psicologia',date:'2099-10-13',weekday:new Date('2099-10-13T12:00:00Z').getUTCDay(),time:'10:00',contactName:'Solicitante de teste',phone:'21999999999',consent:true,requestId:'aabbccdd-0000-4000-8000-001122334455'};
const req=(changes={})=>new Request('https://example.test/api/agenda',{method:'POST',headers:{origin:'https://example.test','content-type':'application/json'},body:JSON.stringify({...sample,...changes})});
const approved=async()=>[{id:sample.studentId,status:'approved'}];
test('real requests fail closed without persistent storage and never fall back to email-only',async()=>{const res=await handleAgenda(req(),env,()=>assert.fail('must not send email without a record'),approved);assert.equal(res.status,503)});
test('unapproved, inactive and duplicate never send',async()=>{for(const rows of [[],[{id:sample.studentId,status:'inactive'}],[{id:sample.studentId,status:'approved'},{id:sample.studentId,status:'approved'}]])assert.equal((await handleAgenda(req(),env,()=>assert.fail(),async()=>rows)).status,403)});
test('bad fields or missing consent never send',async()=>{for(const change of [{phone:'0'},{contactName:'a'},{consent:false},{weekday:9},{time:'99:00'},{date:'2020-01-01'}])assert.equal((await handleAgenda(req(change),env,()=>assert.fail(),approved)).status,400)});
test('registry and storage failures are not success',async()=>{assert.equal((await handleAgenda(req(),env,()=>assert.fail(),async()=>{throw Error()})).status,503);assert.equal((await handleAgenda(req(),env,async()=>Response.json({}, {status:500}),approved)).status,503)});
