import {test} from 'node:test';import assert from 'node:assert/strict';import {ageAt,handleRegistration,RECIPIENTS} from './registration-handler.mjs';
const env={RESEND_API_KEY:'test-not-real',MAIL_FROM:'Projeto <test@example.com>'};
function fields(){const f=new FormData();const year=new Date().getUTCFullYear();for(const [k,v]of Object.entries({studentName:'Aluno de Teste',birthDate:`${year-12}-01-01`,unit:'amavale',guardianName:'Responsável de Teste',guardianEmail:'responsavel@example.com',guardianPhone:'24999999999',relationship:'Mãe',participationConsent:'on',medicalConsent:'on',dataConsent:'on',requestId:'00000000-0000-4000-8000-000000000001'}))f.set(k,v);for(const k of ['studentDocument','guardianDocument','medicalCertificate'])f.set(k,new File(['%PDF-1.4\nDocumento fictício para teste.'],`${k}.pdf`,{type:'application/pdf'}));f.set('photo',new File([new Uint8Array([255,216,255,224])],'photo.jpg',{type:'image/jpeg'}));return f}
function request(f=fields(),origin='https://site.example'){return new Request('https://site.example/api/registrations',{method:'POST',headers:{origin},body:f})}
test('age boundaries, future date, invalid calendar date',()=>{const now=new Date('2026-10-05T15:00:00Z');assert.equal(ageAt('2009-10-06',now),16);assert.equal(ageAt('2009-10-05',now),17);assert.equal(ageAt('2027-01-01',now),-1);assert.equal(ageAt('2012-02-31',now),-1)});
test('unconfigured transport never sends or reports success',async()=>{let called=false;const r=await handleRegistration(request(),{},()=>{called=true});assert.equal(r.status,503);assert.equal(called,false)});
test('rejects foreign origin',async()=>assert.equal((await handleRegistration(request(fields(),'https://other.example'),env)).status,403));
test('rejects age above 17',async()=>{const f=fields();f.set('birthDate','2000-01-01');assert.equal((await handleRegistration(request(f),env)).status,400)});
test('requires valid unit, each consent and each attachment',async()=>{for(const key of ['unit','participationConsent','medicalConsent','dataConsent','studentDocument','guardianDocument','medicalCertificate','photo']){const f=fields();f.delete(key);assert.equal((await handleRegistration(request(f),env)).status,400,key)}});
test('rejects disguised executable and excessive file size',async()=>{const f=fields();f.set('studentDocument',new File(['<script>bad</script>'],'student.pdf',{type:'application/pdf'}));assert.equal((await handleRegistration(request(f),env)).status,400);f.set('studentDocument',new File([new Uint8Array(3*1024*1024+1)],'large.pdf'));assert.equal((await handleRegistration(request(f),env)).status,413)});
test('sends correct recipients, subject, declarations and four attachments through server',async()=>{let body,options;const r=await handleRegistration(request(),env,async(url,o)=>{assert.equal(url,'https://api.resend.com/emails');body=JSON.parse(o.body);options=o;return Response.json({id:'mock-accepted'})});assert.equal(r.status,200);assert.deepEqual(body.to,RECIPIENTS);assert.match(body.subject,/Aluno: Aluno de Teste — Amavale — \d+ anos/);assert.equal(body.attachments.length,4);assert.match(body.text,/foto não está autorizada para divulgação/);assert.equal(body.reply_to,'responsavel@example.com');assert.match(options.headers['Idempotency-Key'],/^registration-/)});
test('provider failure is not presented as success',async()=>{const r=await handleRegistration(request(),env,async()=>Response.json({error:'failure'},{status:500}));assert.equal(r.status,502)});
