import {randomUUID,createHash} from 'node:crypto';
import {fail} from './portal-domain.mjs';
import {PROFESSIONAL_ROLES} from './professional-tools.mjs';
import {calendarTools} from './calendar-tools.mjs';
const now=()=>new Date().toISOString(),active="('pending','confirmed')";
const prefix={amavale:'UND1_',valparaiso:'UND2_','vale-do-carangola':'UND3_'};
const uuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
function instant(day,time){if(typeof day!=='string'||!/^20\d{2}-\d{2}-\d{2}$/.test(day)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))fail('Confira data e horário.');const d=new Date(day+'T'+time+':00-03:00');if(!Number.isFinite(+d)||new Date(day+'T12:00:00Z').toISOString().slice(0,10)!==day)fail('Data inválida.');return d.toISOString()}
export function schedulingTools({db,get,all,run,tx,requireRole,audit,professionalProfile,professionalApproved}){
 db.exec(`CREATE TABLE IF NOT EXISTS appointment_slots(id TEXT PRIMARY KEY,professional_id TEXT NOT NULL REFERENCES professional_profiles(user_id),unit TEXT NOT NULL,start_at TEXT NOT NULL,end_at TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'open' CHECK(state IN ('open','cancelled')),version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY,request_hash TEXT NOT NULL,slot_id TEXT NOT NULL REFERENCES appointment_slots(id),student_id TEXT NOT NULL REFERENCES students(id),requested_by TEXT NOT NULL REFERENCES members(user_id),contact_name TEXT NOT NULL,phone TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','confirmed','cancelled','completed','absent')),reason TEXT NOT NULL DEFAULT '',version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,notice_state TEXT NOT NULL DEFAULT 'pending');
 CREATE UNIQUE INDEX IF NOT EXISTS one_active_booking_per_slot ON bookings(slot_id) WHERE status IN ('pending','confirmed');
 CREATE INDEX IF NOT EXISTS slots_time ON appointment_slots(professional_id,start_at,end_at);
 CREATE INDEX IF NOT EXISTS bookings_student ON bookings(student_id,status);`);
 const professionalAccess=(actor,uid)=>{const m=requireRole(actor,['admin','secretary',...PROFESSIONAL_ROLES]);if(!['admin','secretary'].includes(m.role)&&uid!==actor)fail('Acesso não permitido.',403);const p=professionalProfile(uid);if(!p)fail('Profissional não localizado.',404);return p};
 const studentAccess=(actor,id)=>{const m=requireRole(actor,['admin','secretary','guardian']);if(m.role==='guardian'&&!get('SELECT 1 FROM links WHERE user_id=? AND student_id=?',actor,id))fail('Acesso não permitido.',403);const s=get('SELECT * FROM students WHERE id=?',id);if(!s||s.status!=='approved')fail('Aluno sem aprovação ativa.',403);return s};
 const bookingQuery='SELECT b.*,s.unit,s.start_at,s.end_at,s.professional_id,p.name AS professional_name,m.role AS service,st.name AS student_name FROM bookings b JOIN appointment_slots s ON b.slot_id=s.id JOIN professional_profiles p ON p.user_id=s.professional_id JOIN members m ON m.user_id=p.user_id JOIN students st ON st.id=b.student_id';
 const readBooking=(actor,id)=>{const m=requireRole(actor,['admin','secretary','guardian',...PROFESSIONAL_ROLES]),b=get(bookingQuery+' WHERE b.id=?',id);if(!b)fail('Solicitação não localizada.',404);if(PROFESSIONAL_ROLES.includes(m.role)&&b.professional_id!==actor||m.role==='guardian'&&!get('SELECT 1 FROM links WHERE user_id=? AND student_id=?',actor,b.student_id))fail('Acesso não permitido.',403);return b};
 const safe=b=>{const {request_hash,requested_by,...r}=b;return r};
 return {
  ...calendarTools({all,requireRole,professionalProfile,professionalApproved}),
  async booking(actor,id){return safe(readBooking(actor,id))},
  async slots(actor,uid){professionalAccess(actor,uid);return all(`SELECT s.*,b.id AS booking_id,b.status AS booking_status FROM appointment_slots s LEFT JOIN bookings b ON b.slot_id=s.id AND b.status IN ${active} WHERE s.professional_id=? AND s.end_at>=? ORDER BY start_at LIMIT 500`,uid,new Date(Date.now()-31*86400000).toISOString())},
  async createSlot(actor,p){return tx(()=>{const t=professionalAccess(actor,p.professional_id);if(!professionalApproved(t.user_id)||!t.units.includes(p.unit))fail('Profissional ainda não liberado neste núcleo.',403);const start=instant(p.day,p.start_time),end=instant(p.day,p.end_time);if(start<=now()||end<=start||+new Date(start)>Date.now()+366*86400000||+new Date(end)-new Date(start)>8*3600000)fail('Informe um horário futuro, com fim posterior ao início, em até um ano e com duração de até 8 horas.');if(get("SELECT 1 FROM appointment_slots WHERE professional_id=? AND state='open' AND start_at<? AND end_at>?",t.user_id,end,start))fail('Este intervalo sobrepõe outro horário do profissional.',409);const id=randomUUID();run('INSERT INTO appointment_slots(id,professional_id,unit,start_at,end_at,created_at) VALUES(?,?,?,?,?,?)',id,t.user_id,p.unit,start,end,now());audit(actor,'slot.create:'+id);return get('SELECT * FROM appointment_slots WHERE id=?',id)})},
  async cancelSlot(actor,id,version){return tx(()=>{const s=get('SELECT * FROM appointment_slots WHERE id=?',id);if(!s)fail('Horário não localizado.',404);professionalAccess(actor,s.professional_id);if(s.version!==version||s.state!=='open')fail('Horário alterado. Atualize a lista.',409);if(get(`SELECT 1 FROM bookings WHERE slot_id=? AND status IN ${active}`,id))fail('Há uma solicitação neste horário. A secretaria precisa cancelar e avisar a família primeiro.',409);run("UPDATE appointment_slots SET state='cancelled',version=version+1 WHERE id=?",id);audit(actor,'slot.cancel:'+id)})},
  async availableSlots(actor,studentId){const s=studentAccess(actor,studentId);return all(`SELECT s.id,s.unit,s.start_at,s.end_at,s.professional_id,s.version,p.name AS professional_name,m.role AS service FROM appointment_slots s JOIN professional_profiles p ON p.user_id=s.professional_id JOIN members m ON m.user_id=p.user_id WHERE s.state='open' AND s.start_at>? AND NOT EXISTS(SELECT 1 FROM bookings b WHERE b.slot_id=s.id AND b.status IN ${active}) ORDER BY s.start_at LIMIT 1000`,now()).filter(r=>s.id.startsWith(prefix[r.unit])&&professionalApproved(r.professional_id)&&professionalProfile(r.professional_id).units.includes(r.unit))},
  async bookSlot(actor,slotId,p){return tx(()=>{
   const student=studentAccess(actor,p.student_id);if(!uuid(p.id)||p.consent!==true||typeof p.contact_name!=='string'||p.contact_name.trim().length<3||p.contact_name.length>160||/[\x00-\x1f]/.test(p.contact_name)||typeof p.phone!=='string'||!/^\d{10,11}$/.test(p.phone.replace(/\D/g,'')))fail('Confira o solicitante, WhatsApp e confirmação de ciência.');
   const values={slot_id:slotId,student_id:student.id,requested_by:actor,contact_name:p.contact_name.trim(),phone:p.phone.replace(/\D/g,'')},hash=createHash('sha256').update(JSON.stringify(values)).digest('hex'),old=get('SELECT * FROM bookings WHERE id=?',p.id);if(old){if(old.request_hash!==hash)fail('Protocolo já utilizado.',409);return safe(readBooking(actor,p.id))}
   const slot=get('SELECT * FROM appointment_slots WHERE id=?',slotId);if(!slot||slot.state!=='open'||slot.start_at<=now()||slot.version!==p.version)fail('Horário indisponível. Atualize a agenda.',409);
   const professional=professionalProfile(slot.professional_id);if(!professionalApproved(slot.professional_id)||!professional.units.includes(slot.unit)||!student.id.startsWith(prefix[slot.unit]))fail('Horário indisponível para este aluno.',403);
   if(get(`SELECT 1 FROM bookings WHERE slot_id=? AND status IN ${active}`,slotId))fail('Este horário acaba de ser reservado. Escolha outro.',409);
   if(get(`SELECT 1 FROM bookings b JOIN appointment_slots s ON s.id=b.slot_id WHERE b.student_id=? AND b.status IN ${active} AND s.start_at<? AND s.end_at>?`,student.id,slot.end_at,slot.start_at))fail('O aluno já tem uma solicitação nesse intervalo.',409);
   run("INSERT INTO bookings(id,request_hash,slot_id,student_id,requested_by,contact_name,phone,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'pending',?,?)",p.id,hash,...Object.values(values),now(),now());audit(actor,'booking.request:'+p.id,student.id);return safe(readBooking(actor,p.id));
  })},
  async bookings(actor){const m=requireRole(actor,['admin','secretary','guardian',...PROFESSIONAL_ROLES]),filter=m.role==='guardian'?' WHERE b.student_id IN (SELECT student_id FROM links WHERE user_id=?)':PROFESSIONAL_ROLES.includes(m.role)?' WHERE s.professional_id=?':'';const rows=all(bookingQuery+filter+' ORDER BY s.start_at DESC LIMIT 500',...(filter?[actor]:[]));return rows.map(safe)},
  async reviewBooking(actor,id,p){return tx(()=>{requireRole(actor,['admin','secretary']);const b=readBooking(actor,id);if(!Number.isSafeInteger(p.version)||b.version!==p.version)fail('Solicitação alterada. Atualize a agenda.',409);if(!['confirmed','cancelled','completed','absent'].includes(p.status)||typeof p.reason!=='string'||p.reason.trim().length<3||p.reason.length>500||/[\x00-\x1f]/.test(p.reason))fail('Confira situação e registro administrativo.');const allowed={pending:['confirmed','cancelled'],confirmed:['cancelled','completed','absent'],cancelled:[],completed:[],absent:[]};if(!allowed[b.status].includes(p.status))fail('Mudança de situação inválida.',409);if(p.status==='confirmed'&&(p.contacted!==true||b.start_at<=now()||!professionalApproved(b.professional_id)||!professionalProfile(b.professional_id).units.includes(b.unit)||get('SELECT status FROM students WHERE id=?',b.student_id)?.status!=='approved'))fail('Confira a liberação, o horário futuro e a confirmação por WhatsApp.');if(['completed','absent'].includes(p.status)&&b.end_at>now())fail('Registre o resultado após o horário do atendimento.');run('UPDATE bookings SET status=?,reason=?,version=version+1,updated_at=? WHERE id=?',p.status,p.reason.trim(),now(),id);audit(actor,'booking.'+p.status+':'+id,b.student_id);return safe(readBooking(actor,id))})},
  async claimBookingNotice(actor,id){readBooking(actor,id);return tx(()=>{const b=get('SELECT notice_state FROM bookings WHERE id=?',id);if(!['pending','failed'].includes(b.notice_state))return null;run("UPDATE bookings SET notice_state='sending' WHERE id=?",id);return get('SELECT m.email,b.id,s.start_at FROM bookings b JOIN appointment_slots s ON s.id=b.slot_id JOIN members m ON m.user_id=s.professional_id WHERE b.id=?',id)})},
  async bookingNoticeResult(id,sent){run('UPDATE bookings SET notice_state=? WHERE id=?',sent?'sent':'failed',id)}
 };
}
