import {createHash,randomUUID} from 'node:crypto';
import {fail,validateStudent} from './portal-domain.mjs';
const columns=['guardian_name','guardian_email','guardian_phone','relationship'];
function contactFields(p){const out={};for(const k of columns){const v=p[k]??'';if(typeof v!=='string'||v.length>(k==='guardian_email'?254:160)||/[\x00-\x1f\x7f]/.test(v))fail('Contato inválido.');out[k]=v.trim()}out.guardian_email=out.guardian_email.toLowerCase();if(out.guardian_email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(out.guardian_email))fail('Email inválido.');return out}
export function studentDetails({db,get,all,run,tx,requireRole,audit}){
 const contactColumns=db.prepare('PRAGMA table_info(student_contacts)').all().map(c=>c.name);if(!contactColumns.includes('version'))db.exec('ALTER TABLE student_contacts ADD COLUMN version INTEGER NOT NULL DEFAULT 1');if(!contactColumns.includes('relationship'))db.exec("ALTER TABLE student_contacts ADD COLUMN relationship TEXT NOT NULL DEFAULT ''");
 const regColumns=db.prepare('PRAGMA table_info(registrations)').all().map(c=>c.name);if(!regColumns.includes('source'))db.exec("ALTER TABLE registrations ADD COLUMN source TEXT NOT NULL DEFAULT 'website'");if(!regColumns.includes('source_reference'))db.exec("ALTER TABLE registrations ADD COLUMN source_reference TEXT NOT NULL DEFAULT ''");
 const allowed=(actor,id,write=false)=>{const m=requireRole(actor,write?['admin','secretary']:['admin','secretary','guardian']);if(m.role==='guardian'&&!get('SELECT 1 FROM links WHERE user_id=? AND student_id=?',actor,id))fail('Acesso não permitido.',403);if(!get('SELECT 1 FROM students WHERE id=?',id))fail('Aluno não localizado.',404)};
 const contact=id=>get('SELECT guardian_name,guardian_email,guardian_phone,relationship,version FROM student_contacts WHERE student_id=?',id)||{guardian_name:'',guardian_email:'',guardian_phone:'',relationship:'',version:0};
 return {
  async studentContact(actor,id){allowed(actor,id);return contact(id)},
  async saveStudentContact(actor,id,p){return tx(()=>{allowed(actor,id,true);if(!p||Object.keys(p).some(k=>![...columns,'version'].includes(k))||!Number.isSafeInteger(p.version)||p.version<0)fail('Contato inválido.');if(contact(id).version!==p.version)fail('Contato alterado. Recarregue antes de salvar.',409);const row=contactFields(p);run('INSERT INTO student_contacts(student_id,guardian_name,guardian_email,guardian_phone,relationship,version) VALUES(?,?,?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET guardian_name=excluded.guardian_name,guardian_email=excluded.guardian_email,guardian_phone=excluded.guardian_phone,relationship=excluded.relationship,version=excluded.version',id,...columns.map(k=>row[k]),p.version+1);audit(actor,'student.contact',id);return contact(id)})},
  async importContacts(actor,rows){return tx(()=>{requireRole(actor,['admin']);if(!Array.isArray(rows)||!rows.length||rows.length>500)fail('Contatos inválidos.');let count=0;const seen=new Set();for(const r of rows){if(!r||!/^UND[1-3]_\d{6}$/.test(r.id)||seen.has(r.id)||!get('SELECT 1 FROM students WHERE id=?',r.id))fail('Aluno inválido nos contatos.');seen.add(r.id);const row=contactFields(r);if(get('SELECT 1 FROM student_contacts WHERE student_id=?',r.id))continue;run('INSERT INTO student_contacts(student_id,guardian_name,guardian_email,guardian_phone,relationship) VALUES(?,?,?,?,?)',r.id,...columns.map(k=>row[k]));audit(actor,'student.contact.seed',r.id);count++}return count})},
  async manualRegistration(actor,p){return tx(()=>{requireRole(actor,['admin','secretary']);if(!p||Object.keys(p).some(k=>!['id','student_name','birth_date','unit',...columns,'consent_version','source_reference','checked'].includes(k)))fail('Inscrição inválida.');if(p.checked!==true)fail('Confira as declarações e a origem do cadastro.');if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(p.id)||!['amavale','valparaiso','vale-do-carangola'].includes(p.unit))fail('Protocolo ou núcleo inválido.');const student=validateStudent({id:'UND1_000001',name:p.student_name,birth_date:p.birth_date,status:'pending',version:0}),c=contactFields(p);if(c.guardian_name.length<3||!c.guardian_email||c.guardian_phone.length<8||!c.relationship)fail('Complete os dados do responsável.');for(const key of ['consent_version','source_reference'])if(typeof p[key]!=='string'||p[key].trim().length<3||p[key].length>300||/[\x00-\x1f]/.test(p[key]))fail('Informe a origem e a versão das declarações conferidas.');const row={id:p.id,student_name:student.name,birth_date:student.birth_date,unit:p.unit,...c,consent_version:p.consent_version.trim(),source_reference:p.source_reference.trim(),source:'staff'};const hash=createHash('sha256').update(JSON.stringify(row)).digest('hex'),old=get('SELECT * FROM registrations WHERE id=?',row.id);if(old){if(old.payload_hash!==hash)fail('Protocolo já utilizado.',409);return {id:old.id}}
   const values={...row,payload_hash:hash,documents:'[]',created_at:new Date().toISOString()},keys=Object.keys(values);run('INSERT INTO registrations('+keys.join(',')+') VALUES('+keys.map(()=>'?').join(',')+')',...keys.map(k=>values[k]));audit(actor,'registration.manual:'+row.id);return {id:row.id};})},
  async registrationUpload(actor,id,version,d){return tx(()=>{requireRole(actor,['admin','secretary']);const r=get('SELECT * FROM registrations WHERE id=?',id);if(!r)fail('Inscrição não localizada.',404);if(r.status==='approved')fail('Use a ficha do aluno aprovado para anexar documentos.',409);if(!Number.isSafeInteger(version)||r.version!==version)fail('Inscrição alterada. Recarregue antes de enviar.',409);const docs=JSON.parse(r.documents);if(docs.length>=60)fail('Limite de versões atingido. Procure a administração.');docs.push({...d,created_by:actor,created_at:new Date().toISOString()});run('UPDATE registrations SET documents=?,version=version+1 WHERE id=?',JSON.stringify(docs),id);audit(actor,'registration.upload:'+id);return d.id})},
  async contactExport(actor){requireRole(actor,['admin','secretary']);audit(actor,'contacts.export');return all('SELECT s.id,s.name,c.guardian_name,c.guardian_email,c.guardian_phone,c.relationship,c.version FROM students s LEFT JOIN student_contacts c ON c.student_id=s.id ORDER BY s.id')}
 };
}
