import {randomUUID,createHash} from 'node:crypto';
import {fail,ageAt} from './portal-domain.mjs';
export const UNITS=['amavale','valparaiso','vale-do-carangola'];
const PREFIX={amavale:'UND1_',valparaiso:'UND2_','vale-do-carangola':'UND3_'};
const profileKeys=['name','phone','belt_degree','certificate_issuer','certificate_date','first_aid_until','availability','notes'];
function text(v,label,max=200,min=0){if(typeof v!=='string'||v.trim().length<min||v.length>max||/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(v))fail('Confira '+label+'.');return v.trim()}
function date(v,optional=false){if(optional&&v==='')return v;if(typeof v!=='string'||!/^(19|20)\d{2}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(+new Date(v+'T12:00:00Z'))||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)fail('Confira a data.');return v}
function version(v){if(!Number.isSafeInteger(v)||v<0)fail('Versão inválida.');return v}
export function teacherTools({db,get,all,run,tx,requireRole,audit}){
 db.exec(`CREATE TABLE IF NOT EXISTS teacher_profiles(user_id TEXT PRIMARY KEY REFERENCES members(user_id),name TEXT NOT NULL,phone TEXT NOT NULL,belt_degree TEXT NOT NULL DEFAULT '',certificate_issuer TEXT NOT NULL DEFAULT '',certificate_date TEXT NOT NULL DEFAULT '',first_aid_until TEXT NOT NULL DEFAULT '',availability TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',status TEXT NOT NULL CHECK(status IN ('pending','verified')),version INTEGER NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS teacher_units(user_id TEXT NOT NULL REFERENCES teacher_profiles(user_id),unit TEXT NOT NULL,PRIMARY KEY(user_id,unit));
 CREATE TABLE IF NOT EXISTS teacher_documents(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES teacher_profiles(user_id),kind TEXT NOT NULL CHECK(kind IN ('photo','black_belt_diploma','first_aid_certificate')),object_path TEXT UNIQUE NOT NULL,mime TEXT NOT NULL,size INTEGER NOT NULL,original_name TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES members(user_id),created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY,request_hash TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('incident','injury')),unit TEXT NOT NULL,student_id TEXT REFERENCES students(id),occurred_at TEXT NOT NULL,category TEXT NOT NULL,description TEXT NOT NULL,actions TEXT NOT NULL,guardian_contact TEXT NOT NULL,referral TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES members(user_id),created_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','closed')),version INTEGER NOT NULL DEFAULT 1);
 CREATE TABLE IF NOT EXISTS report_updates(id TEXT PRIMARY KEY,report_id TEXT NOT NULL REFERENCES reports(id),note TEXT NOT NULL,status TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES members(user_id),created_at TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS reports_unit ON reports(unit,created_at);`);
 const unitsFor=uid=>all('SELECT unit FROM teacher_units WHERE user_id=? ORDER BY unit',uid).map(r=>r.unit);
 const profile=uid=>{const r=get("SELECT p.*,m.email,m.active FROM teacher_profiles p JOIN members m USING(user_id) WHERE p.user_id=? AND m.role='teacher'",uid);return r?{...r,active:!!r.active,units:unitsFor(uid)}:undefined};
 function requireUnit(actor,unit){const m=requireRole(actor,['admin','secretary','teacher']);if(!UNITS.includes(unit))fail('Núcleo inválido.');if(m.role==='teacher'&&(profile(actor)?.status!=='verified'||!unitsFor(actor).includes(unit)))fail('Professor sem liberação para este núcleo.',403);return m}
 const readTeacher=(actor,uid)=>{const m=requireRole(actor,['admin','teacher']);if(m.role==='teacher'&&actor!==uid)fail('Acesso não permitido.',403);const p=profile(uid);if(!p)fail('Professor não localizado.',404);return p};
 function readReport(actor,id){const m=requireRole(actor,['admin','secretary','teacher']),r=get('SELECT r.*,s.name AS student_name,m.email AS author_email FROM reports r LEFT JOIN students s ON s.id=r.student_id JOIN members m ON m.user_id=r.created_by WHERE r.id=?',id);if(!r)fail('Relato não localizado.',404);requireUnit(actor,r.unit);if(m.role==='teacher'&&r.created_by!==actor)fail('Acesso não permitido.',403);return r}
 return {
  requireUnit,
  async availableUnits(actor){const m=requireRole(actor,['admin','secretary','teacher']);return m.role==='teacher'?(profile(actor)?.status==='verified'?unitsFor(actor):[]):UNITS},
  async unitRoster(actor,unit){requireUnit(actor,unit);return all("SELECT id,name,birth_date FROM students WHERE substr(id,1,5)=? AND status='approved' ORDER BY name,id",PREFIX[unit]).map(s=>({id:s.id,name:s.name,age:ageAt(s.birth_date)}))},
  async teachers(actor){const m=requireRole(actor,['admin','teacher']);return m.role==='teacher'?[profile(actor)].filter(Boolean):all("SELECT user_id FROM members WHERE role='teacher' ORDER BY email").map(m=>profile(m.user_id)).filter(Boolean)},
  async teacher(actor,uid){return readTeacher(actor,uid)},
  async saveTeacher(actor,uid,p){return tx(()=>{
   requireRole(actor,['admin']);if(!p||Object.keys(p).some(k=>![...profileKeys,'email','units','status','version','checked'].includes(k)))fail('Campos do professor inválidos.');
   const row=Object.fromEntries(profileKeys.map(k=>[k,text(p[k]??'',k,k==='notes'||k==='availability'?1000:200,k==='name'?3:k==='phone'?8:0)]));
   if(!/^\+?[\d ()-]{8,30}$/.test(row.phone))fail('Confira o telefone.');date(row.certificate_date,true);date(row.first_aid_until,true);if(row.certificate_date&&+new Date(row.certificate_date+'T12:00:00Z')>Date.now()+86400000)fail('A data do diploma não pode estar no futuro.');
   if(!Array.isArray(p.units)||p.units.length>3||new Set(p.units).size!==p.units.length||p.units.some(u=>!UNITS.includes(u)))fail('Núcleos inválidos.');
   if(!['pending','verified'].includes(p.status))fail('Situação inválida.');version(p.version);
   const old=uid?profile(uid):null;if(uid&&!old)fail('Professor não localizado.',404);if((old?.version||0)!==p.version)fail('Cadastro alterado. Recarregue antes de salvar.',409);
   const email=text(p.email,'email',254,3).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail('Email inválido.');if(old&&email!==old.email)fail('O email de acesso não pode ser alterado neste formulário.');
   if(p.status==='verified'&&(p.checked!==true||!p.units.length||!row.belt_degree||!row.certificate_issuer||!row.certificate_date||!uid||['photo','black_belt_diploma'].some(k=>!get('SELECT 1 FROM teacher_documents WHERE user_id=? AND kind=?',uid,k))))fail('Para liberar, confira foto, diploma, graduação, emissor, data e núcleos.');
   if(!old){if(get('SELECT 1 FROM members WHERE email=?',email))fail('Email já cadastrado. Use uma conta exclusiva para o professor.',409);uid=randomUUID();run("INSERT INTO members(user_id,email,role) VALUES(?,?,'teacher')",uid,email)}
   const columns=['user_id',...profileKeys,'status','version','updated_at'],values={user_id:uid,...row,status:p.status,version:p.version+1,updated_at:new Date().toISOString()};
   run('INSERT INTO teacher_profiles('+columns.join(',')+') VALUES('+columns.map(()=>'?').join(',')+') ON CONFLICT(user_id) DO UPDATE SET '+columns.slice(1).map(k=>k+'=excluded.'+k).join(','),...columns.map(k=>values[k]));
   run('DELETE FROM teacher_units WHERE user_id=?',uid);for(const u of p.units)run('INSERT INTO teacher_units VALUES(?,?)',uid,u);audit(actor,'teacher.save:'+uid);return profile(uid);
  })},
  async teacherDocuments(actor,uid){readTeacher(actor,uid);return all('SELECT * FROM teacher_documents WHERE user_id=? ORDER BY created_at DESC',uid)},
  async teacherDocument(actor,id){const d=get('SELECT * FROM teacher_documents WHERE id=?',id);if(!d)fail('Documento não localizado.',404);readTeacher(actor,d.user_id);return d},
  async addTeacherDocument(actor,uid,d){return tx(()=>{readTeacher(actor,uid);if(!['photo','black_belt_diploma','first_aid_certificate'].includes(d.kind))fail('Categoria inválida.');run('INSERT INTO teacher_documents VALUES(?,?,?,?,?,?,?,?,?)',d.id,uid,d.kind,d.object_path,d.mime,d.size,d.original_name,actor,new Date().toISOString());run("UPDATE teacher_profiles SET status='pending',version=version+1,updated_at=? WHERE user_id=?",new Date().toISOString(),uid);audit(actor,'teacher.document:'+d.id);return d.id})},
  async reports(actor,unit){const m=requireUnit(actor,unit);return all('SELECT id,kind,unit,student_id,occurred_at,category,status,version,created_by,created_at FROM reports WHERE unit=?'+(m.role==='teacher'?' AND created_by=?':'')+' ORDER BY occurred_at DESC LIMIT 200',...[unit,...(m.role==='teacher'?[actor]:[])])},
  async report(actor,id){const r=readReport(actor,id);audit(actor,'report.read:'+id,r.student_id);const {request_hash,...safe}=r;return {...safe,updates:all('SELECT u.*,m.email AS author_email FROM report_updates u JOIN members m ON m.user_id=u.created_by WHERE report_id=? ORDER BY created_at,id',id)}},
  async createReport(actor,p){return tx(()=>{
   if(!p||Object.keys(p).some(k=>!['id','kind','unit','student_id','occurred_at','category','description','actions','guardian_contact','referral'].includes(k)))fail('Relato inválido.');
   requireUnit(actor,p.unit);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(p.id)||!['incident','injury'].includes(p.kind))fail('Relato inválido.');
   if(typeof p.occurred_at!=='string'||!/^20\d{2}-\d{2}-\d{2}T([01]\d|2[0-3]):[0-5]\d$/.test(p.occurred_at))fail('Confira data e hora.');date(p.occurred_at.slice(0,10));if(+new Date(p.occurred_at+'-03:00')>Date.now()+60000)fail('A ocorrência não pode estar no futuro.');
   const injury=p.kind==='injury',student_id=injury?text(p.student_id,'aluno',20,1):null;
   if(injury){const s=get('SELECT * FROM students WHERE id=?',student_id);if(!s||!s.id.startsWith(PREFIX[p.unit])||s.status!=='approved')fail('Aluno indisponível neste núcleo.',403)}else if(p.student_id)fail('Use relato de lesão para registros individuais.');
   const row={id:p.id,kind:p.kind,unit:p.unit,student_id,occurred_at:p.occurred_at,category:text(p.category,'categoria ou região afetada',100,3),description:text(p.description,'descrição objetiva',3000,10),actions:text(p.actions,'providências',3000,5),guardian_contact:injury?text(p.guardian_contact,'contato com responsável',1000,3):'',referral:injury?text(p.referral,'encaminhamento',1000,3):'',created_by:actor};
   const hash=createHash('sha256').update(JSON.stringify(row)).digest('hex'),old=get('SELECT * FROM reports WHERE id=?',p.id);if(old){if(old.created_by!==actor||old.request_hash!==hash)fail('Protocolo já utilizado.',409);return {id:old.id,status:old.status}}
   const values={...row,request_hash:hash,created_at:new Date().toISOString()},columns=Object.keys(values);run('INSERT INTO reports('+columns.join(',')+') VALUES('+columns.map(()=>'?').join(',')+')',...columns.map(k=>values[k]));audit(actor,'report.create:'+p.id,student_id);return {id:p.id,status:'open'};
  })},
  async updateReport(actor,id,p){return tx(()=>{const r=readReport(actor,id),m=requireRole(actor,['admin','secretary','teacher']);if(!p||Object.keys(p).some(k=>!['version','note','status'].includes(k)))fail('Atualização inválida.');version(p.version);if(r.version!==p.version)fail('Relato alterado. Recarregue antes de salvar.',409);if(!['open','closed'].includes(p.status)||m.role==='teacher'&&p.status!==r.status)fail('Somente a administração ou secretaria encerra ou reabre o relato.',403);const note=text(p.note,'acompanhamento',3000,5);run('INSERT INTO report_updates VALUES(?,?,?,?,?,?)',randomUUID(),id,note,p.status,actor,new Date().toISOString());run('UPDATE reports SET status=?,version=version+1 WHERE id=?',p.status,id);audit(actor,'report.update:'+id,r.student_id);return {id,status:p.status}})},
  async reportsExport(actor,unit){requireRole(actor,['admin','secretary']);requireUnit(actor,unit);audit(actor,'report.export:'+unit);return all('SELECT r.id,r.kind,r.unit,r.student_id,s.name AS student_name,r.occurred_at,r.category,r.description,r.actions,r.guardian_contact,r.referral,r.status,r.version,m.email AS author_email,r.created_at FROM reports r LEFT JOIN students s ON s.id=r.student_id JOIN members m ON m.user_id=r.created_by WHERE r.unit=? ORDER BY r.created_at',unit).map(r=>({...r,updates_json:JSON.stringify(all('SELECT note,status,created_by,created_at FROM report_updates WHERE report_id=? ORDER BY created_at,id',r.id))}))}
 };
}
