import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {whatsappNotices} from './whatsapp-notices.mjs';
function fixture(t){
 const db=new DatabaseSync(':memory:');t.after(()=>db.close());db.exec("CREATE TABLE members(user_id TEXT PRIMARY KEY,email TEXT,role TEXT,active INTEGER);INSERT INTO members VALUES('a','a@example.test','admin',1),('t','t@example.test','teacher',1),('g','g@example.test','guardian',1);CREATE TABLE project_contact(id INTEGER PRIMARY KEY,phone TEXT);INSERT INTO project_contact VALUES(1,'+5524987741447')");
 const get=(s,...p)=>db.prepare(s).get(...p),all=(s,...p)=>db.prepare(s).all(...p),run=(s,...p)=>db.prepare(s).run(...p),tx=f=>{db.exec('BEGIN IMMEDIATE');try{const r=f();db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}},requireRole=(id,roles)=>{const m=get('SELECT * FROM members WHERE user_id=? AND active=1',id);if(!m||!roles.includes(m.role))throw Object.assign(Error('Forbidden'),{status:403});return m};
 const env={},sent=[],f={rows:[{kind:'absence',issue_id:'one',user_id:'t'}]};f.transport=async(url,options)=>{sent.push({url,...options,body:JSON.parse(options.body)});return Response.json({messages:[{id:'fake'}]})};
 const deps={db,get,all,run,tx,requireRole,audit:()=>{},env,transport:(...p)=>f.transport(...p),targets:()=>f.rows};f.api=whatsappNotices(deps);f.newWorker=()=>whatsappNotices(deps);f.env=env;f.sent=sent;f.db=db;
 f.connect=async()=>{Object.assign(env,{WHATSAPP_ACCESS_TOKEN:'test-only',WHATSAPP_PHONE_NUMBER_ID:'123456',WHATSAPP_API_VERSION:'v99.0',WHATSAPP_TEMPLATE:'approved_test',WHATSAPP_LANGUAGE:'pt_BR',WHATSAPP_SENDER_PHONE:'+5524987741447'});const s=await f.api.whatsappSettings('a');await f.api.saveWhatsappSettings('a',{phone:s.phone,enabled:true,version:s.version})};
 f.consent=()=>f.api.saveWhatsappRecipient('a',{user_id:'t',phone:'+5524988881111',accepted:true,version:0});return f;
}
test('WhatsApp nasce pausado, não expõe segredo e exige conexão compatível antes de ativar',async t=>{
 const f=fixture(t),s=await f.api.whatsappSettings('a');assert.equal(s.enabled,false);assert.equal(s.connected,false);assert.equal(s.phone,'+5524987741447');await f.api.deliverWhatsappNotices();assert.equal(f.sent.length,0);await assert.rejects(f.api.saveWhatsappSettings('a',{phone:s.phone,enabled:true,version:s.version}),{status:409});await f.connect();assert.doesNotMatch(JSON.stringify(await f.api.whatsappSettings('a')),/test-only/);
});
test('WhatsApp: só administrador configura; consentimento obrigatório, opt-out e número editável',async t=>{
 const f=fixture(t);await assert.rejects(f.api.whatsappSettings('t'),{status:403});await assert.rejects(f.api.saveWhatsappRecipient('a',{user_id:'g',phone:'+5524988881111',accepted:true,version:0}),{status:400});await f.connect();await f.api.deliverWhatsappNotices();assert.equal(f.sent.length,0);await f.consent();await f.api.saveWhatsappRecipient('a',{user_id:'t',phone:'+5524988881111',accepted:false,version:1});await f.api.deliverWhatsappNotices();assert.equal(f.sent.length,0);
 const s=await f.api.whatsappSettings('a'),changed=await f.api.saveWhatsappSettings('a',{phone:'+5524999991111',enabled:true,version:s.version});assert.equal(changed.enabled,false);assert.equal(changed.connected,false);await assert.rejects(f.api.saveWhatsappSettings('a',{phone:s.phone,enabled:false,version:s.version}),{status:409});
});
test('WhatsApp: envio oficial mínimo, uma vez por ocorrência mesmo com dois processos e reinício',async t=>{
 const f=fixture(t);await f.connect();await f.consent();await Promise.all([f.api.deliverWhatsappNotices(),f.newWorker().deliverWhatsappNotices()]);assert.equal(f.sent.length,1);const p=f.sent[0];assert.equal(p.url,'https://graph.facebook.com/v99.0/123456/messages');assert.equal(p.body.type,'template');assert.equal(p.body.to,'5524988881111');assert.equal(p.body.template.name,'approved_test');assert.equal(p.body.template.components,undefined);await f.newWorker().deliverWhatsappNotices();assert.equal(f.sent.length,1);assert.equal((await f.api.whatsappSettings('a')).deliveries[0].status,'accepted');
});
test('WhatsApp: falha ambígua não repete automaticamente; resolução e revogação cancelam antes de enviar',async t=>{
 const f=fixture(t);await f.connect();await f.consent();f.rows=[];await f.api.deliverWhatsappNotices();assert.equal(f.sent.length,0);f.rows=[{kind:'rollcall',issue_id:'two',user_id:'t'}];f.transport=async()=>{f.sent.push('attempt');throw Error('timeout')};await f.api.deliverWhatsappNotices();await f.newWorker().deliverWhatsappNotices();assert.equal(f.sent.length,1);assert.equal((await f.api.whatsappSettings('a')).deliveries[0].status,'review');f.db.exec("UPDATE members SET active=0 WHERE user_id='t'");f.rows.push({kind:'absence',issue_id:'three',user_id:'t'});await f.api.deliverWhatsappNotices();assert.equal(f.sent.length,1);
});
