import {randomUUID} from 'node:crypto';
import {fail} from './portal-domain.mjs';
import {UNITS} from './teacher-tools.mjs';
import {localDay} from './professional-tools.mjs';
const managers=['admin','secretary'],statuses=['present','absent','justified','unmarked'];
const now=()=>new Date().toISOString();
function text(v,max,min=0){if(typeof v!=='string'||v.trim().length<min||v.length>max||/[\x00-\x1f\x7f]/.test(v))fail('Confira os campos do cadastro.');return v.trim()}
function date(v){if(typeof v!=='string'||!/^20\d{2}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(+new Date(v+'T12:00:00Z'))||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v)fail('Data inválida.');return v}
export function workforceTools({db,get,all,run,tx,requireRole,audit}){
 db.exec(`CREATE TABLE IF NOT EXISTS monitors(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL,notes TEXT NOT NULL,active INTEGER NOT NULL CHECK(active IN(0,1)),version INTEGER NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS monitor_units(monitor_id TEXT NOT NULL REFERENCES monitors(id),unit TEXT NOT NULL,PRIMARY KEY(monitor_id,unit));
 CREATE TABLE IF NOT EXISTS workforce_sessions(id TEXT PRIMARY KEY,group_id TEXT NOT NULL REFERENCES class_groups(id),unit TEXT NOT NULL,day TEXT NOT NULL,start_time TEXT NOT NULL,end_time TEXT NOT NULL,label TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES members(user_id),created_at TEXT NOT NULL,UNIQUE(group_id,day));
 CREATE TABLE IF NOT EXISTS workforce_attendance(session_id TEXT NOT NULL REFERENCES workforce_sessions(id),person_key TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN('teacher','monitor')),status TEXT NOT NULL DEFAULT 'unmarked' CHECK(status IN('present','absent','justified','unmarked')),note TEXT NOT NULL DEFAULT '',version INTEGER NOT NULL DEFAULT 0,updated_by TEXT REFERENCES members(user_id),updated_at TEXT,PRIMARY KEY(session_id,person_key));
 CREATE TABLE IF NOT EXISTS workforce_changes(id TEXT PRIMARY KEY,session_id TEXT NOT NULL,person_key TEXT NOT NULL,previous_status TEXT NOT NULL,status TEXT NOT NULL,previous_note TEXT NOT NULL,note TEXT NOT NULL,version INTEGER NOT NULL,actor TEXT NOT NULL REFERENCES members(user_id),created_at TEXT NOT NULL,FOREIGN KEY(session_id,person_key) REFERENCES workforce_attendance(session_id,person_key));`);
 const readMonitor=id=>{const m=get('SELECT * FROM monitors WHERE id=?',id);return m?{...m,active:!!m.active,units:all('SELECT unit FROM monitor_units WHERE monitor_id=? ORDER BY unit',id).map(r=>r.unit)}:null};
 const unitCheck=u=>{if(!UNITS.includes(u))fail('Núcleo inválido.')};
 const roster=unit=>[
  ...all("SELECT 'teacher:'||p.user_id AS id,p.name,'teacher' AS role FROM teacher_profiles p JOIN members m USING(user_id) JOIN teacher_units u USING(user_id) WHERE m.active=1 AND m.role='teacher' AND p.status='verified' AND u.unit=?",unit),
  ...all("SELECT 'monitor:'||p.id AS id,p.name,'monitor' AS role FROM monitors p JOIN monitor_units u ON u.monitor_id=p.id WHERE p.active=1 AND u.unit=?",unit)
 ].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));
 function session(actor,id){requireRole(actor,managers);const s=get('SELECT * FROM workforce_sessions WHERE id=?',id);if(!s)fail('Chamada da equipe não localizada.',404);return s}
 return {
  async monitors(actor){requireRole(actor,managers);return all('SELECT id FROM monitors ORDER BY name,id').map(r=>readMonitor(r.id))},
  async saveMonitor(actor,id,p){return tx(()=>{requireRole(actor,managers);if(!p||Object.keys(p).some(k=>!['name','email','phone','notes','active','version','units'].includes(k))||!Number.isSafeInteger(p.version)||p.version<0||typeof p.active!=='boolean')fail('Cadastro inválido.');const row={name:text(p.name,160,3),email:text(p.email||'',254).toLowerCase(),phone:text(p.phone,30,8),notes:text(p.notes||'',1000)};if(row.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(row.email)||!/^\+?[\d ()-]{8,30}$/.test(row.phone))fail('Confira email e telefone.');if(!Array.isArray(p.units)||!p.units.length||p.units.length>3||new Set(p.units).size!==p.units.length||p.units.some(u=>!UNITS.includes(u)))fail('Selecione os núcleos de atuação.');const old=id?readMonitor(id):null;if(id&&!old)fail('Monitor não localizado.',404);if((old?.version||0)!==p.version)fail('Cadastro alterado. Recarregue antes de salvar.',409);if(row.email&&get('SELECT 1 FROM monitors WHERE email=? AND id<>?',row.email,id||''))fail('Já existe um monitor com este email.',409);id ||= randomUUID();run('INSERT INTO monitors VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,email=excluded.email,phone=excluded.phone,notes=excluded.notes,active=excluded.active,version=excluded.version,updated_at=excluded.updated_at',id,row.name,row.email,row.phone,row.notes,Number(p.active),p.version+1,now());run('DELETE FROM monitor_units WHERE monitor_id=?',id);for(const u of p.units)run('INSERT INTO monitor_units VALUES(?,?)',id,u);audit(actor,'monitor.save:'+id);return readMonitor(id)})},
  async workforceRoster(actor,unit){requireRole(actor,managers);unitCheck(unit);return roster(unit)},
  async workforceSessions(actor,unit){requireRole(actor,managers);unitCheck(unit);return all('SELECT * FROM workforce_sessions WHERE unit=? ORDER BY day DESC,start_time DESC LIMIT 200',unit)},
  async createWorkforceSession(actor,p){return tx(()=>{requireRole(actor,managers);if(!p||Object.keys(p).some(k=>!['group_id','day','people'].includes(k)))fail('Chamada inválida.');date(p.day);if(p.day>localDay())fail('A chamada da equipe só pode ser aberta na data da aula ou depois.');const g=get('SELECT * FROM class_groups WHERE id=?',p.group_id);if(!g||!g.active||!JSON.parse(g.weekdays).includes(new Date(p.day+'T12:00:00Z').getUTCDay()))fail('Confira turma ativa e dia da aula.');if(!Array.isArray(p.people)||!p.people.length||p.people.length>100||new Set(p.people).size!==p.people.length||p.people.some(v=>typeof v!=='string'))fail('Selecione a equipe prevista para esta aula.');const old=get('SELECT * FROM workforce_sessions WHERE group_id=? AND day=?',g.id,p.day);if(old){const previous=all('SELECT person_key FROM workforce_attendance WHERE session_id=?',old.id).map(r=>r.person_key);if(previous.length!==p.people.length||p.people.some(k=>!previous.includes(k)))fail('Esta aula já tem uma chamada da equipe. Abra a chamada existente para conferir a lista.',409);return old}const people=new Map(roster(g.unit).map(r=>[r.id,r]));if(p.people.some(k=>!people.has(k)))fail('Há pessoas sem liberação ou fora deste núcleo.',403);const id=randomUUID();run('INSERT INTO workforce_sessions VALUES(?,?,?,?,?,?,?,?,?)',id,g.id,g.unit,p.day,g.start_time,g.end_time,g.label,actor,now());for(const key of p.people){const r=people.get(key);run('INSERT INTO workforce_attendance(session_id,person_key,name,role) VALUES(?,?,?,?)',id,key,r.name,r.role)}audit(actor,'workforce.open:'+id);return session(actor,id)})},
  async workforceAttendance(actor,id){const lesson=session(actor,id);return {lesson,people:all('SELECT * FROM workforce_attendance WHERE session_id=? ORDER BY name,person_key',id)}},
  async markWorkforceAttendance(actor,id,rows){return tx(()=>{const s=session(actor,id);if(s.day>localDay())fail('Não é possível marcar presença futura.');if(!Array.isArray(rows)||!rows.length||rows.length>100)fail('Chamada inválida.');const seen=new Set();for(const r of rows){if(!r||typeof r.id!=='string'||seen.has(r.id)||!statuses.includes(r.status)||!Number.isSafeInteger(r.version)||r.version<0)fail('Marcações inválidas.');seen.add(r.id);const note=text(r.note||'',500),old=get('SELECT * FROM workforce_attendance WHERE session_id=? AND person_key=?',id,r.id);if(!old)fail('Pessoa fora da lista desta aula.',403);if(old.version!==r.version)fail('A chamada foi alterada por outra pessoa. Reabra e confira antes de salvar.',409);if(old.status===r.status&&old.note===note)continue;run('UPDATE workforce_attendance SET status=?,note=?,version=version+1,updated_by=?,updated_at=? WHERE session_id=? AND person_key=?',r.status,note,actor,now(),id,r.id);run('INSERT INTO workforce_changes VALUES(?,?,?,?,?,?,?,?,?,?)',randomUUID(),id,r.id,old.status,r.status,old.note,note,r.version+1,actor,now());audit(actor,'workforce.'+r.status+':'+id+':'+r.id)}return rows.length})},
  async workforceHistory(actor,id){session(actor,id);return all('SELECT c.*,m.email AS author_email FROM workforce_changes c JOIN members m ON m.user_id=c.actor WHERE session_id=? ORDER BY created_at,id',id)},
  async workforceExport(actor,unit,from,to){requireRole(actor,managers);unitCheck(unit);date(from);date(to);if(from>to||(+new Date(to)-new Date(from))/86400000>366)fail('Selecione um período de até um ano.');audit(actor,'workforce.export:'+unit);return all('SELECT s.day AS date,s.start_time,s.end_time,s.label AS class,s.unit,a.person_key,a.name,a.role,a.status,a.note,a.version,a.updated_at,m.email AS recorded_by FROM workforce_attendance a JOIN workforce_sessions s ON s.id=a.session_id LEFT JOIN members m ON m.user_id=a.updated_by WHERE s.unit=? AND s.day BETWEEN ? AND ? ORDER BY s.day,s.start_time,a.name',unit,from,to)}
 };
}
